### ISSUE TITLE
Forgit doesn't respect delta themes

### ISSUE THREAD

**Issue by ejolly** [wfxr/forgit#100]
## Check list

- [X] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [X] I have the latest version of forgit
- [X] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

## Problem / Steps to reproduce

Configuring [delta](https://github.com/dandavison/delta) to use a specific color theme works when using delta by itself or by invoking git commands directly (e.g. `git diff`), but I can't seem to get forgit to change the colors rendered in the fzf preview window no matter what I do.

It doesn't seem to pick up delta settings in `~/.gitconfig` and I've even tried specifying options in my `~/.zshrc`, e.g. `export FORGIT_FZF_DEFAULT_OPTS= "--preview='delta --light'"` or `export FORGIT_LOG_FZF_OPTS= "--preview='delta --light'"`

**Comment by wfxr** [comment]
`forgit` just reads `core.pager` in `.gitconfig` as its pager. I don't known why it does't work for you. Can you show your `$forgit_pager` here?

```
echo $forgit_pager
```

**Comment by ejolly** [comment]
Sorry closing this it was an error in my `.gitconfig` which I copied from from delta's README. It shows `theme = ''` in its example `.gitconfig` whereas the option has been renamed `syntax-theme=''` to match the command-line flag
