### ISSUE TITLE
What's the protocol for pull requests?

### ISSUE THREAD

**Issue by m42martin** [wfxr/forgit#101]
I haven't contributed to open source projects in the past and thought I should ask about your preferences first.

I added a function to handle switching branches.  I only use bash in WSL and haven't made the same changes to the fish script.  Also, it's not ready for integration yet because I stripped out some of the FZF opts to get it working quickly for me.    At any rate, I'd like to contribute if possible.

Thanks.

## Check list

- [X] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [ ] I have the latest version of forgit
- [X] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [X] Windows
    - [X] Others: WSL
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

**Comment by cjappl** [comment]
Hi @m42martin. Excited to have you contribute!

I'd say just submit it if you get it working. Be sure to try to match the general code style, and follow good conventions (nice short well named functions, etc)

It will be reviewed by @wfxr who is the main developer of the tool. No real worries if you can't test it in fish, that's my job to convert things over and maintain parity. If you can get it going in fish, bonus points to you! Normally, it's pretty similar to bash and you can find examples in the code on how to convert it.

At any rate, just fill out the PR template we have, describe what you've done and we will review. If you want to have any "pre-discussion" on an issue, feel free to open a feature request and we can discuss there, or we can just talk on the PR.

let me know if you have any more questions or need assistance. Happy to help.

Please close this issue if you're satisfied!

**Comment by wfxr** [comment]
Thank you @cjappl . You made a great reply. 

It's a good habit to open an issue to discussion before submitting PRs. Sometimes one's understanding of the project may not be consistent with the project author or maintainers. So if you want to make a big change, make sure to open an issue first. This may reduce the frustration of PR rejection.

@m42martin Back to your specific question:

> I added a function to handle switching branches. ...

Welcome to contribute. However, it should be reminded that fogit is not intended for completion. In most cases shell's  completion mechanism works well.

If what your want is just use fzf to complete git's branch, one alias is enough (issue: #26):
```bash
alias gbr='git checkout $(git branch | fzf | tr -d "*")'
```

There also be a fzf based completion plugin you may intrested in: https://github.com/Aloxaf/fzf-tab

If not, can you describe the feature in more detail, or better to show a screenshot or GIF?

**Comment by m42martin** [comment]
Thanks @wfxr and @cjappl.  I'm not sure if my idea for branch switching makes sense after @wfxr 's comment.  Let me think about it for a while.  I may create an issue ticket to discuss later this week; maybe this weekend.

Cheers for the nice snippet ideas @wfxr !
