### ISSUE TITLE
forgit zsh functions should be autoloaded

### ISSUE THREAD

**Issue by MenkeTechnologies** [wfxr/forgit#110]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [ ] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
forgit:: functions are defined in forgit.plugin.zsh.  This slows down startup and increases memory overhead.  They should be in a dir in fpath and autoloaded so they are only defined when used.  The plugin file should put this dir in fpath and autoload all the function files. This is zsh best practice.

**Comment by wfxr** [comment]
@MenkeTechnologies Thank you.

> This slows down startup and increases memory overhead.

I don't think forgit significantly slows down the startup of zsh.
```zsh
❯ hyperfine -w 10 'zsh nothing.zsh' 'zsh forgit.plugin.zsh'
Benchmark #1: zsh nothing.zsh
  Time (mean ± σ):       5.8 ms ±   0.2 ms    [User: 3.2 ms, System: 2.8 ms]
  Range (min … max):     5.7 ms …   7.3 ms    387 runs

Benchmark #2: zsh forgit.plugin.zsh
  Time (mean ± σ):       8.6 ms ±   0.2 ms    [User: 5.5 ms, System: 3.5 ms]
  Range (min … max):     8.4 ms …  10.0 ms    286 runs
```

`nothing.zsh`:
```zsh
#!/usr/bin/env zsh
echo
```

Sourcing `forgit.plugin.zsh` use extra **2.8ms** than sourcing `nothing.zsh`. Does it have any major impact on startup speed? I do not think so. If you are really not satisfied with your zsh startup speed, you should try [zinit](https://github.com/zdharma/zinit) or [zsh-defer](https://github.com/romkatv/zsh-defer). I use they to load about 50 plugins(include some very slow ones like `pip completion --zsh` and `pipenv --completion`) within less than 20ms.

Also don’t think memory usage is something worth noting.
```zsh
❯ ls -l forgit.plugin.zsh
-rwxr-xr-x 1 wenxuan users 9554 Sep  6 09:50 forgit.plugin.zsh
```
The entire file is only 9,954 bytes. I know this is not the exact memory usage of forgit, but it shows to a certain extent that its memory usage is not worth mentioning.

The last and most important thing is `forgit` share the code between zsh and bash. `forgit.plugin.sh` is a symbol link to `zsh nothing.zsh`. I'm afriad your suggestions are not suitable for bash. I don't want to maintain different codes for bash and zsh for these insubstantial improvements.

**Comment by MenkeTechnologies** [comment]
I already use zinit.  The advantages of autoloading go beyond CPU time.  It is also reduced memory usage.  Also the plugin is more modular and maintainable with all the functions in one directory as opposed to stuffed in one file.  Also it is a principal Zsh design to use autoloading.  It is a Zsh antipattern when frameworks like OMZ do not autoload their functions and dump their functions defs in one file.

If bash compatibility is so important (what bash framework are you supporting?) you can just source all the files for each function in the autoload dir.  In each file just add a check to see if the shell is zsh and then exec the function if so.

**Comment by wfxr** [comment]
Sorry, I don’t agree with you. Of course we can even split each function into a separate executable file, and then add them into the PATH to avoid loading it at shell startup. But the question is, what are the real benefits of doing so? 

If loading a plugin is really time-consuming or memory-consuming, it is appropriate to use this specific lazy loading technique (not the only way, just one of). But it is obviously not necessary for `forgit`. Loading speed and memory usage have never been a problem for this plugin, as I explained before. And I don't think split every functions into different files will increase the maintainability of the project.
