### ISSUE TITLE
gi command not working f

### ISSUE THREAD

**Issue by dcontt00** [wfxr/forgit#115]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
When using gi and selecting an option to add to the .gitignore file, the file is not created. I don't know why this happens, I installed forgit following the README and before installing I had intalled fzf properly.

**Comment by wfxr** [comment]
@dcontt00  Can you paste your command here? I need to known how you call `gi` command.

**Comment by dcontt00** [comment]
I reinstalled fzf and forgit and it already works for me. The command I was using was `gi >> .gitignore`, so that the content of the gi selection was written to the .gitignore. Thank you anyway

**Comment by wfxr** [comment]
You're welcome.
