### ISSUE TITLE
Compatible with a fish plugin manager

### ISSUE THREAD

**Issue by FollieHiyuki** [wfxr/forgit#116]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

Hi. Thanks for a nice shell plugin.
I have some suggestions: maybe moving forgit.plugin.fish into a directory named conf.d so that it can be easily installed,updated and autoloaded with a plugin manager like fisher or oh my fish. And the file doesn't need to be executable.

**Comment by cjappl** [comment]
Hi @AoHiyuki. This is a great idea.

Unfortunately I don't have a lot of experience using or developing fish plugins for these systems. Do you have any experience? If so, please feel free to do a PR on this!

Otherwise it may be a little bit while I figure out how to make it work :)

**Comment by AoHiyuki** [comment]
Hi @cjappl. I made it working with Fisher. Fairly simple as I described.
As I'm not familiar with Oh My Fish, it may take a while for me to figure out.
1 question though: do you mind if I separate the plugin into autoload and functions, since issue #110 ?

**Comment by wfxr** [comment]
@AoHiyuki The main reason I object to splitting `forgit.plugin.zsh` is that it makes it difficult for zsh and bash to share code, or you have to do a lot of dirty work. This however does not make the plugin easier to use or maintain.

But for the fish version, it is not compatible with zsh or bash from the beginning (As you can see, it is a translation of the bash/zsh version, not a symbol link). Therefore, I am not opposed to splitting it. @cjappl is responsible for maintaining the fish version, so you can freely discuss solutions with him. @AoHiyuki

**Comment by wfxr** [comment]
`fisher` support has been implemented. I think this issue can be closed now @cjappl

**Comment by cjappl** [comment]
Sounds good.

Thanks for the good work @wfxr  and @AoHiyuki

**Comment by AoHiyuki** [comment]
> I just caught a minor issue. Didn't check things out thoroughly :(
> forgit.plugin.fish appears in 2 places (even if it is just a symlink). So when installed with Fisher it will be copied to both conf.d and functions (the file in conf.d to ~/.config/fish/conf.d and the main file to ~/.config/fish/functions)
> It works with no problems, but fish now will register a function named forgit.plugin (that doesn't do anything) since the file is there in the functions directory.

Only 1 minor issue @cjappl , but it doesn't affect anything badly.

**Comment by cjappl** [comment]
Any idea what the fix would be for this?

Thanks for catching it

**Comment by AoHiyuki** [comment]
I would only keep the file inside conf.d directory and delete the other one @cjappl .

**Comment by wfxr** [comment]
@AoHiyuki I used symbol link to reuse the shorten url.

fisher's mechanism for loading plugins seems a bit special.  I wonder if it support the plugin placed in a subdirectory? Like this layout:
```
.
├── fish
│  └── conf.d
│     └── forgit.plugin.fish
├── forgit.plugin.sh -> forgit.plugin.zsh
├── forgit.plugin.zsh
├── LICENSE
└── README.md
```

**Comment by wfxr** [comment]
@AoHiyuki I replaced the link with actual file. You can update and test if it works fine.

Now `forgit`'s project layout seems already compatible with [omf](https://github.com/oh-my-fish/oh-my-fish):

```fish
omf install https://github.com/wfxr/forgit
```

@cjappl Would you like to submit a PR to [this repo](https://github.com/oh-my-fish/packages-main) so that users can install forgit by using name instead of full url?

**Comment by AoHiyuki** [comment]
@wfxr yeah it works fine. Thanks for the quick fix.

Both Fisher and OMF utilize the conf.d directory, so we can already install `forgit` with either one. Fisher copies it directly to ~/.config/fish/conf.d so it works with no problem. OMF in the other hand sources the file when we start a new shell on its own, that leads to the problem I mentioned.

**Comment by wfxr** [comment]
Got it. @AoHiyuki

**Comment by wfxr** [comment]
@AoHiyuki Changed all variables which should be global to global. I think this is the rightway to solve the problem.

**Comment by AoHiyuki** [comment]
I just installed OMF to test it and it works. You can update README for both plugin managers now @wfxr . I didn't make the change earlier since I wasn't sure enough whether making them global could break things.

**Comment by wfxr** [comment]
Updated url from `git.io/forgit.fish` to `git.io/forgit-fish` because as of Sep 2020 we can no longer request git.io outdated or incorrect shortened URLs be released by GitHub Support.

https://github.blog/changelog/2020-09-23-git-io-urls-no-longer-released-by-github-support/

**Comment by cjappl** [comment]
Requested that we be added to the public repo:
https://github.com/oh-my-fish/packages-main/pull/126

**Comment by cjappl** [comment]
Will close when we are in there.

**Comment by FollieHiyuki** [comment]
Hi again. Fisher made an update a few months back.

The syntax to install should be `fisher install wfxr/forgit` now

**Comment by cjappl** [comment]
I'm just going to close this. We have done what we can and now we are waiting for an (extremely slow) external dependency.
