### ISSUE TITLE
Problem with "antigen purge"

### ISSUE THREAD

**Issue by yahkun** [wfxr/forgit#120]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
![image](https://user-images.githubusercontent.com/22726424/97112527-bac79880-171f-11eb-96f9-0f4d2f6e3ee6.png)

**Comment by cjappl** [comment]
Hi @yahkun would you please provide more information on what you are doing, and what the issue you are having is?

This issue does not have enough information to act currently.

**Comment by yahkun** [comment]
Sorry, I should post this issue to `antigen` 😁
