### ISSUE TITLE
Delta side-by-side not displayed correctly on fzf preview window 

### ISSUE THREAD

**Issue by mrswats** [wfxr/forgit#121]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I have been using forgit for a while and so far I love it! A while ago I switched to delta to display the diff however if I toggle the side-to-side option in delta in the preview window looks all squished to the left of the preview window with very narrow panels for each side of the diff. However, this only happens in forgit as if I run ``git diff`` I see the side to side no problems spanning the whole window. (I attached a screenshot)

![DeepinScreenshot_select-area_20201031111037](https://user-images.githubusercontent.com/3410779/97776593-b78e3b80-1b69-11eb-8232-89c1a4d2a1b8.png)

Am I missing something here? Is this a fzf option maybe? I have been looking for days and I cannot find anything 😅

Thank you for your help in advance, I love this tool very much, keep up the good work!

**Comment by wfxr** [comment]
@mrswats Sorry for the late reply. Can you show your git diff pager? (`git config --global core.pager` )

**Comment by mrswats** [comment]
That would be `delta` and in my git config i have `side-by-side = true`.

**Comment by crivotz** [comment]
@mrswats same problem here.

![xxxxxx](https://user-images.githubusercontent.com/3275600/98085673-f5e36d80-1e7d-11eb-8eca-218bb29a271b.png)


```
[core]
  pager = delta
[interactive]
  diffFilter = delta --color-only
[delta]
  features = side-by-side line-numbers decorations
  whitespace-error-style = 22 reverse
  syntax-theme = gruvbox
[delta "decorations"]
  commit-decoration-style = bold yellow box ul
  file-style = bold yellow ul
  file-decoration-style = none
```

**Comment by mrswats** [comment]
Yes, this is a similar configuration I have.

**Comment by wfxr** [comment]
I doubt whether `delta` can still correctly handle the width when the ouput is not a tty. You can try the following two commands:

```
git diff | delta --side-by-side
```
```
git diff | delta --side-by-side | less
```

**Comment by mrswats** [comment]
You are correct! The first one displays delta's side-by-side correctly taking up all the terminal width evenly for each split while the second one indeed does whatever the hell it wants.

Thank you for your help, I will look at delta's issues and investigate on the other side and will report back if I find something useful.

**Comment by mrswats** [comment]
Okay, just right after comenting the other issue the first open issue in delta is this one: https://github.com/dandavison/delta/issues/368 which is exactly the issue I reported.

**Comment by wfxr** [comment]
A workaround based on @Kr1ss-XD 's comment:

> NOTE I've just noticed a paragraph in the fzf(1) manual, which might be relevant for this ticket :
> 
>  > fzf exports $FZF_PREVIEW_LINES and $FZF_PREVIEW_COLUMNS so that they represent the exact size of the preview window. (It also overrides $LINES and $COLUMNS with the same values but they can be reset by the default shell, so prefer to refer to the ones with FZF_PREVIEW_ prefix.)
> 
> It's in the "Preview" section.


```zsh
export FORGIT_PAGER='delta --side-by-side -w $FZF_PREVIEW_COLUMNS' 
```

The only cons of this solution is it need to be set manually instead of reading it from git's config.  

@mrswats @crivotz

**Comment by mrswats** [comment]
Could we maybe add this somewhere in the docs while it gets fixed in delta? (assuming it has to be fixed somewhere else)

**Comment by crivotz** [comment]
Thank you very much

**Comment by mrswats** [comment]
Just for future reference, it seems that this feature will be implemented soon(ish) and is currently being discussed here: https://github.com/dandavison/delta/issues/359

**Comment by mrswats** [comment]
And with both workaround and discussion over in delta I will be closing this issue.

**Comment by wfxr** [comment]
@mrswats Thanks for your help and suggestion. I will pin this issue until it gets fixed more elgantly so that others with the same problem will easily find the solution.

BTW I like delta's `side-by-side` view but it is not suitable when the window is narrow. So I use the following config that can auto switch to classic view when the with of window is less than 160. Hope it can help you too.

```
pager = { [ $COLUMNS -lt 160 ] && delta || delta --side-by-side -w ${FZF_PREVIEW_COLUMNS:-$COLUMNS} }
```

**Comment by horseinthesky** [comment]
@wfxr Hi.
`export FORGIT_PAGER='delta --side-by-side -w ${FZF_PREVIEW_COLUMNS:-$COLUMNS}'` doesn't work for me.

Could you pls explain what section of gitconfig to put `pager = delta --side-by-side -w ${FZF_PREVIEW_COLUMNS:-$COLUMNS}`

Here is part of my gitconfig related to dalta
```
[pager]
  diff = delta
  log = delta
  reflog = delta
  show = delta

[stash]
  showStat = false
  showPatch = true

[delta]
  features = side-by-side line-numbers navigate
  syntax-theme = Monokai Extended
  plus-style = "syntax #004d00"
  minus-style = "syntax #4d0000"
  line-numbers-plus-style = "#b8bb26"
  line-numbers-minus-style = "#fb4934"
  line-numbers-zero-style = "#665c54"

[interactive]
  diffFilter = delta --color-only
```

At the moment it looks like this
<img width="941" alt="Screenshot_1" src="https://user-images.githubusercontent.com/19948672/125318713-c78a2c00-e342-11eb-80dd-78fe85e27487.png">
<img width="949" alt="Screenshot_2" src="https://user-images.githubusercontent.com/19948672/125318716-c822c280-e342-11eb-9d36-f7a97e623822.png">

**Comment by DanielFGray** [comment]
@wfxr this worked for me
```
[core]
pager = bash -c 'delta -s -w ${FZF_PREVIEW_COLUMNS:-$COLUMNS}'
```
it seems that git uses `sh` to run this command, and `${var:-word}` is a bashism, so this explicitly uses bash

**Comment by Kr1ss-XD** [comment]
Nice !   If that is the issue, it might also suffice to simply omit the `:` :

```gitconfig
[core]
	pager	=	delta --side-by-side --width ${FZF_PREVIEW_COLUMNS-$COLUMNS}
```

I think that's valid `sh` syntax. Not tested though - I'm on mobile right now.

**Comment by horseinthesky** [comment]
> Tried all above config's but doesn't help.

Forgit does know nothing about `delta`. You must provide the info about how many columns you have in your terminal window somehow

Check out my custom git fzf functions. I use `delta` pager with the appropriate info
https://github.com/horseinthesky/dotfiles/blob/master/files/zsh/fzf-git-functions.zsh#L12

**Comment by 0xRZ** [comment]
This solution stopped working for me on `fzf 0.35.1`:
`pager = delta --width ${FZF_PREVIEW_COLUMNS-$COLUMNS}`

It says `error: The argument '--width <N>' requires a value but none was supplied` when trying to open diff with forgit::diff

**Comment by cjappl** [comment]
@0xRZ how about 

https://github.com/wfxr/forgit/issues/121#issuecomment-968118124

This one works for me

**Comment by 0xRZ** [comment]
@cjappl nope. does not work for me

**Comment by cjappl** [comment]
Ok, you will probably have to dig in and do some troubleshooting yourself. It seems like there's something in your config that's different from mine.

@carlfriedrich any ideas here?

**Comment by carlfriedrich** [comment]
@0xRZ Have you exported your `FZF_PREVIEW_COLUMNS` and `COLUMNS` variables? Otherwise `forgit` has no access to them.

**Comment by 0xRZ** [comment]
@carlfriedrich i didnt get exported. Added 
```
export COLUMNS
export FZF_PREVIEW_COLUMNS
```

**Comment by carlfriedrich** [comment]
@0xRZ Great to hear that it works!
