### ISSUE TITLE
No suggestion for cherry-pick on <TAB>

### ISSUE THREAD

**Issue by fedoranvar** [wfxr/forgit#125]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

No suggestion (based on `git branch`) for `forgit::cherry::pick` on <TAB>, so I have to manually type branch name

Reproduction:
```
$ forgit::cherry::pick <TAB>
```

**Comment by wfxr** [comment]
@fedoranvar Sorry, forgit functions does not support shell completion. This might not be a big problem, because most forgit functions don't need to receive parameters.
