### ISSUE TITLE
forgit::diff has stopped working

### ISSUE THREAD

**Issue by hrai** [wfxr/forgit#127]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] Others: Ubuntu on WSL 2
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

`forgit::diff` does not open interactive diff anymore.

`forgit::add` prints `Nothing to add.` even though there are changed files.
![image](https://user-images.githubusercontent.com/4055444/101587634-b5f14680-3a38-11eb-85bd-c15f92a94e9e.png)

**Comment by wfxr** [comment]
Does `fzf` works ok? And what's the exit code? (print by `forgit::diff; echo $?`)

**Comment by hrai** [comment]
@wfxr yeah `fzf` works fine 
![image](https://user-images.githubusercontent.com/4055444/102424015-645f4200-405e-11eb-8afe-e7dbc55427e1.png)

`forgit::diff; echo $?` prints 1

**Comment by hrai** [comment]
I just realised that I have a `sed` alias.

Unaliasing fixed the issue. :)
