### ISSUE TITLE
extra blank line between result when grepping git log results

### ISSUE THREAD

**Issue by petobens** [wfxr/forgit#129]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

Using `forgit::log` with the `-G` flag to grep commit messages results in extra blank lines between results. See the following gif were I `glg` alias is given by:
```bash
alias gl=forgit::log
alias glg='gl -G'
```

![forgit](https://user-images.githubusercontent.com/2583971/103156821-a0478500-478b-11eb-9cc1-21361467da8c.gif)

**Comment by wfxr** [comment]
Maybe you want to disable git log graph?
```bash
FORGIT_LOG_GRAPH_ENABLE=false glo -G gdk
```

**Comment by petobens** [comment]
Neat. Thanks!
