### ISSUE TITLE
Implement gcb in fish

### ISSUE THREAD

**Issue by cjappl** [wfxr/forgit#133]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- Shell
    - [x] fish

## Problem / Steps to reproduce

Task to recreate #131 in fish.

@wfxr  will hopefully get to it this weekend!

**Comment by wfxr** [comment]
@cjappl The related PR has been merged. Thank you!
