### ISSUE TITLE
`grb` (interactive rebase) breaks zsh prompt

### ISSUE THREAD

**Issue by levito** [wfxr/forgit#138]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X (10.15.7)
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh (5.7.1)
    - [ ] fish

## Problem / Steps to reproduce

Running an interactive rebase with `grb` breaks the zsh prompt.

To reproduce, after running `grb`, e. g.:
- Try to close the session with `ctrl+d` – It won't close but init an autocomplete
- Other commands like `ls -l` have broken output with heavily misaligned lines
- Prompts like powerlevel10k have their prompt character moved to the right after running `rgb` (see https://github.com/levito/dotfiles/blob/master/.zshrc to reproduce)

**Comment by wfxr** [comment]
@levito It seems this problem is caused by the editor. Are you using `vim` as the editor for git?

**Comment by levito** [comment]
Hey @wfxr, thanks for the quick response! It looks like this fixed the issue!

Btw.: when trying to find the cause, I disabled almost every line in my zshrc, but I didn't change my git editor... 😅

**Comment by wfxr** [comment]
Glad to see that. Also thank you for reporting this!
