### ISSUE TITLE
git log copy binding (ctrl+y) includes a newline

### ISSUE THREAD

**Issue by wren** [wfxr/forgit#141]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
After using the default keybinding to copy the commit hash, the clipboard contains a newline after the hash. This can lead to some weird scenarios for users where a newline runs the command immediately.

1. `git log`
2. <kbd>ctrl</kbd> + <kbd>y</kbd>
3. paste somewhere

**Comment by wfxr** [comment]
@wren Thank you for reporting this. It should have been fixed by the latest commit. Please update and check if it works for you.

**Comment by wren** [comment]
@wfxr Works great. Thanks for the quick fix!
