### ISSUE TITLE
glo does not work with multi-selection 

### ISSUE THREAD

**Issue by puneetse** [wfxr/forgit#144]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce
glo does not behave intuitively when `--multi` is passed to fzf for multi-selection and multiple commits are selected. 

Steps to reproduce:
1. `set FORGIT_LOG_FZF_OPTS --multi`
2. `glo -- some/file/path`
3. Select multiple commits (tab, shift+tab, or shift + mouse scroll)
4. Hit enter 
5. Only the highlighted commit is displayed and the rest of the selection is ignored. 

I would expect all the selected commits to be shown in a single buffer or loop over the selected commits being shown one by one.

I'm using `git log --oneline -- some/file/path | fzf --multi`as a comparison for expected behavior

**Comment by wfxr** [comment]
@puneetse Thanks for your report.

Well, `glo` was intentionally designed to work under the single selection mode. In fact `glo` uses `enter` to preview the diff content with full-screen. And you will back to fzf after you quit the preview.

https://github.com/wfxr/forgit/blob/416ac0308f4ec4a81ccf26e4ecbf7ea98b87b3db/forgit.plugin.zsh#L25-L26

For your example `git log --oneline -- some/file/path | fzf --multi`, fzf will quit after you hit `enter` which is different from the `glo`'s behavior. There needs some tricks to support multi selection for previewing but it should be possible I think.

You can keep this issue open before I have a try.
