### ISSUE TITLE
Add support for `git reflog`

### ISSUE THREAD

**Issue by wren** [wfxr/forgit#155]
## Feature request
I've become so dependent on forgit in my daily workflow that I honestly just get cranky when I have to do something without it. I recently had to use `git reflog` and found that there's no forgit command for it. Admittedly, reflog isn't a command that I need often, but when I do there's really no replacement, and I think forgit would be very useful.

## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

**Comment by wfxr** [comment]
Hi @wren, Thanks for your feedback! I'm glad that forgit can help you. I understand your needs. But reflog is indeed a command that is rarely used. If we keep adding commands like `reflog`, `forgit` will become more and more large and unwieldy. This is inconsistent with it's goal. `forgit` just uses fzf to make some interactive improvment to the **commonly used** git command. I want to keep it simple and light.

You can even extend it easily if you have some knownledge about shell and fzf. Or you can take a look at [lazygit](https://github.com/jesseduffield/lazygit) or [gitui](https://github.com/extrawurst/gitui). They both are great heavyweight git tui tools. forgit is no comparable with them in terms of completeness of functions. They should be able to help you solve the similiar needs I think.

**Comment by wren** [comment]
@wfxr It's completely understandable if my feature request is out of scope for `forgit`. Thanks anyway for considering it!

**Comment by cjappl** [comment]
@wren Can you describe what the reflog command would do? Would it help you diff across refs? Have you check out a specific one?

To be completely honest, I didn't know about this command until this issue, and I've been using it pretty frequently now, so I'd be curious what you had in mind with this feature request

**Comment by wren** [comment]
> @wren Can you describe what the reflog command would do?

When I first ran this, I expected it to behave like `git log` in forgit since the output is nearly identical. For example:

```sh
$ g log --oneline -5
  b896449 (HEAD -> main, origin/main) update whichkey for local leader in nvim
  ebee436 update nvim plugins
  a3af4b7 fix weird bug in packer for nvim
  5009299 update some lsp plugins and settings for nvim
  aa6eaa3 ls colors, encryption aliases, and hub in zsh


$ g reflog -5
  b896449 (HEAD -> main, origin/main) HEAD@{0}: pull --rebase: Fast-forward
  cb49c99 HEAD@{1}: commit (amend): move nix home-manager to stable channel
  3ed0bc7 HEAD@{2}: commit: move nix home-manager to stable
  bb6d297 HEAD@{3}: commit: add some zsh and tmux aliases and bindings
  95e0949 HEAD@{4}: reset: moving to HEAD
```

So, my request was to have forgit support `git reflog` the same way it works with `git log`. In this case, I'm referring to an fzf list of commits with a preview window to show the diff; pressing enter to show the full diff in less; ctrl+y to copy the commit hash; etc.

Of course, there are reflog-specific features that could be added (like parsing the `HEAD@{0}` and `pull`/`commit`/`reset`/whatever part of the output), but even just copying the current log functionality would already be very useful in my opinion.
