### ISSUE TITLE
gi not working with fish

### ISSUE THREAD

**Issue by julienpierini** [wfxr/forgit#161]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

fzf version 0.27.2
fish version 3.3.1
forgit version 4.3.0

When using `gi` with fish nothing is display, fatal error.

```
fatal: No such file or directory
find: No such file or directory
```
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32954578/127877838-c9c23308-3612-4fca-97bf-8258a35ed357.png">

**Comment by cjappl** [comment]
@julienpierini will you check with the most recent? I believe I just fixed it.

Also, something we should probably document at some point, you actually write to your gitignore using redirection

```
gi >> .gitignore
```

if you just run gi, it will just preview the output for you and not write anything

**Comment by julienpierini** [comment]
I confirm this is working now 👍
