### ISSUE TITLE
Horizontal split. Useful with delta side-by-side

### ISSUE THREAD

**Issue by pablospe** [wfxr/forgit#162]
Is there a way to do horizontal split instead of vertical? For delta with `side-by-side` mode would work better.

## Check list

- [X] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [X] I have the latest version of forgit
- [X] I have searched through the existing issues

## Environment info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

**Comment by wfxr** [comment]
@pablospe You can specify fzf options for forgit: https://github.com/wfxr/forgit#fzf-options

**Comment by pablospe** [comment]
Unfortunately I wasn't able to find the correct option to do this.

**Comment by pablospe** [comment]
ok, maybe with `--preview-window 'down:75%'` or similar?

**Comment by wfxr** [comment]
@pablospe That's right. These options are for `fzf`. Detailed descriptions can be found at `fzf`'s man page.
