### ISSUE TITLE
ga preview not working with fish

### ISSUE THREAD

**Issue by flanaras** [wfxr/forgit#170]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

When using the latest version with fish, installed either with `fisher install wfxr/forgit` or `source (curl -sSL git.io/forgit-fish | psub)`, `ga` shows the following error.

```
fish: $\ is not a valid variable in fish.
        sed -e 's/^\\\"//' -e 's/\\\"\$//'  # removes surrounding quotes
                                      ^
```

This is on a folder that contains a git repository.

similar to #168

**Comment by cjappl** [comment]
Yeah, agreed something changed recently. Let me see if I can look into it

**Comment by flanaras** [comment]
> @flanaras will you download the local file and try this as a fix? Just to test it before I commit it:
> 
> Replace the part in `function forgit::add -d "git add selector"` with this:
> 
> ```
>         set extract_file "
>         sed 's/^[[:space:]]*//' |           # remove leading whitespace
>         cut -d ' ' -f 2- |                       # cut the line after the M or ??, this leaves just the filename
>         sed 's/.* -> //' 
>     "
> ```

Hi @cjappl, this makes the `ga` preview to work again.

Thanks for the timely response.
