### ISSUE TITLE
`fisher update` installs update to `forgit` for current shell session, but it's not permanent

### ISSUE THREAD

**Issue by macintacos** [wfxr/forgit#177]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [ ] I have the latest version of forgit -> read more about this below, this is literally the problem I think :)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

So I noticed today that `gcb` was showing some weird control characters like `[m` in its output, like so:

![CleanShot iTerm2 2022-01-25 at 14 49 22](https://user-images.githubusercontent.com/8128941/151048987-213bd1a1-4718-4b25-80df-71c7addd38f4.png)

I decided that perhaps I hadn't updated `forgit` in a while, so I used `fisher update` to update my plugins. After I did that, the aforementioned issue went away. Yay!

However, when I start a new shell session, the issue comes back. For what it's worth, I'm not 100% sure if this is a `fisher` issue or a `forgit` issue, so I'm opening an issue in both repositories to see if I can get to the bottom of this (I'll reference this issue in that repo when I open it). Any ideas what could be causing this?

**Comment by macintacos** [comment]
I just want to note some observations that I have after debugging this a bit further.

- Everything from what I can tell is installed correctly in my `functions` path by `fisher`, and it all works fine.
- When I run `fisher remove wfxr/forgit`, start a new shell, and then `fisher install wfxr/forgit`, the `gcb` command shows everything output "properly" (I don't see those `[m` characters and such). However, when I start a new `fish` shell, the problem demonstrated above comes back.
- The above observation makes me think that there is some issue with the way that this plugin loads. I'm going to look into that a little bit more.

**Comment by macintacos** [comment]
Closing this out, I'll reopen if I can't figure it out.

**Comment by cjappl** [comment]
Thanks for the help tracking this down!!

Sorry I’ve been MIA. I’m also not super well versed in fisher.

If you find anything, keep us updated. Thanks again.
