### ISSUE TITLE
Forgit gcb does not show the master branch anymore

### ISSUE THREAD

**Issue by NullSense** [wfxr/forgit#179]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
gcb does not list the master branch

**Comment by cjappl** [comment]
Thanks for the report!

Do you have a link to a public repo you can reproduce this with? I’m still seeing master when I use gcb.

**Comment by NullSense** [comment]
Sorry for the late reply, it turns out the master branch is present but for some reason the matching algorithm put it a whole page up (I have a lot of branches on this project) instead of immediately giving me the suggestion (it doesn't seem to be sorting on branch naming)

https://github.com/wfxr/forgit/issues/180 actual issue

**Comment by cjappl** [comment]
Closing, thanks for confirming
