### ISSUE TITLE
Add fish shell support

### ISSUE THREAD

**Issue by m-rey** [wfxr/forgit#18]
Hello
I've noticed that zsh is supported. Are there plans to support fish shell, too?

**Comment by wfxr** [comment]
Sorry but I don't want to keep two pieces of code. Because `zsh` and `bash` can share the same code but fish can't.
Myabe You can have a look at this [repo](https://github.com/EfforiaKnight/fizzygit). It was copied from the `forgit`(early edition).

**Comment by cjappl** [comment]
@m-rey just a heads up if you didnn't see it, I completed this work! Try it out and let me know if you have any issues

**Comment by cjappl** [comment]
Also tagging @leiserfg
