### ISSUE TITLE
Sorting branches by last checkout

### ISSUE THREAD

**Issue by timsofteng** [wfxr/forgit#181]
Hello. 
Is it possible to add sorting git branches by last checkout?
I want to see branch where I was working before current brunch above it in fzf list.

**Comment by cjappl** [comment]
This is for which command?

gcb?

**Comment by cjappl** [comment]
Cool, @wfxr have any issue with this?

I can look into it when I get a chance, but as long as he approves, we accept PRs @timsofteng ! I would guess this isn't too big or hard of a change

**Comment by wfxr** [comment]
@timsofteng It's hard to implement branch LRU sorting unless git provide a api. But you can always use `-` as the last branch:

```
$ git switch -                 # switch to the latest branch
$ git rebase -                 # rebase from the latest branch
```
