### ISSUE TITLE
No aliases after zplug install

### ISSUE THREAD

**Issue by selfagency** [wfxr/forgit#184]
## Check list

- [X] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [X] I have the latest version of forgit
- [X] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

## Problem / Steps to reproduce

None of the default aliases specified in the docs are available in the shell after installing with zplug. I can only access commands with the full name or using git aliases (after I configued them).

```
forgit::add           forgit::checkout::branch  forgit::checkout::commit  forgit::checkout::file    forgit::checkout::tag  forgit::cherry::pick  forgit::clean        forgit::diff         forgit::fixup  forgit::ignore  forgit::ignore::clean  forgit::ignore::get
forgit::ignore::list  forgit::ignore::update    forgit::info              forgit::inside_work_tree  forgit::log            forgit::rebase        forgit::reset::head  forgit::stash::show  forgit::warn      
```

**Comment by timoleistner** [comment]
How did you solve it?
