### ISSUE TITLE
Preview command cannot be customized in command-specific options

### ISSUE THREAD

**Issue by carlfriedrich** [wfxr/forgit#185]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I would like to customize the preview command that it used in `glo`, so I thought I could easily add it to `FORGIT_LOG_FZF_OPTS` like [described in the README](https://github.com/wfxr/forgit/blob/master/README.md#fzf-options). This does not work, however, because the `--preview` option is not included in `FZF_DEFAULT_OPTS` but a hard-coded argument to `fzf`:

https://github.com/wfxr/forgit/blob/e0d3552d4597f42c5c965daa5abd79845990f63a/forgit.plugin.zsh#L33

Is there a specific reason for this, or would it be possible to move the `--preview="$cmd"` argument into the `opts` between line 27 and 28?

https://github.com/wfxr/forgit/blob/e0d3552d4597f42c5c965daa5abd79845990f63a/forgit.plugin.zsh#L23-L33

That way I would be able to override the preview command in `FORGIT_LOG_FZF_OPTS`.

This also affects most other commands with their corresponding variables:

- `FORGIT_DIFF_FZF_OPTS`
- `FORGIT_ADD_FZF_OPTS`
- `FORGIT_RESET_HEAD_FZF_OPTS`
- `FORGIT_STASH_FZF_OPTS`
- `FORGIT_REBASE_FZF_OPTS`
- `FORGIT_FIXUP_FZF_OPTS`
- `FORGIT_CHECKOUT_FILE_FZF_OPTS`
- `FORGIT_CHECKOUT_BRANCH_FZF_OPTS`
- `FORGIT_CHECKOUT_TAG_FZF_OPTS`
- `FORGIT_COMMIT_FZF_OPTS`
- `FORGIT_IGNORE_FZF_OPTS`

(BTW why doesn't `forgit::cherry::pick` have a corresponding variable?)

If nothing speaks against that, I could provide a pull request for it.

**Comment by carlfriedrich** [comment]
Since I don't see any drawbacks in making the proposed change, I just filed a PR #186 to fix this. Would love to see this merged.

**Comment by carlfriedrich** [comment]
Sorry, I accidentally closed this when I merged the change into my own fork. Reopen it to merge it here as well.
@wfxr Let me know if you accept the change.

**Comment by wfxr** [comment]
@carlfriedrich Nice improvement, thanks for your contribution!
