### ISSUE TITLE
Add formula to homebrew

### ISSUE THREAD

**Issue by arihant2math** [wfxr/forgit#194]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [ ] Windows
- Shell: All

## Problem / Steps to reproduce

There is no homebrew formula for forgit, this is my default package manager.

**Comment by cjappl** [comment]
@arihant2math I think this is a great idea, and seeing as you have 9 thumbs up for it, seems like a lot of people agree!

Any chance you have the time to write up a PR for it? I think the only requirements is that it installs the correct bindings for each applicable shell (fish/bash/zsh). Not sure how brew deals with commands like this that are kind of aliases of other commands.

**Comment by vicendominguez** [comment]
There is a previous step to do here. We need versioning in forgit. `Brew` [doesn't like unversioned-things®](https://docs.brew.sh/Acceptable-Formulae#we-dont-like-install-scripts-that-download-unversioned-things)

**Comment by arihant2math** [comment]
@vicendominguez Created #233 for that

**Comment by carlfriedrich** [comment]
I like this idea as well and will put this on my agenda for the near future.

**Comment by aasutossh** [comment]
```ruby
class Forgit < Formula
  desc "Interactive git commands in the terminal"
  homepage "https://github.com/wfxr/forgit"
  url "https://github.com/wfxr/forgit/releases/download/23.01.0/forgit-23.01.0.tar.gz"
  sha256 "2f7b0b4defbeb0945c5e644283749e62d901f1f1389eaddf9c591ab7091a27ae"
  license "MIT"

  depends_on "fzf"

  def install
    bin.install "bin/git-forgit" => "forgit"
  end

  test do
    system "which", "forgit"
  end
end
```
is enough.
I have https://github.com/aasutossh/homebrew-core/tree/forgit-formula ready to do the PR. You can do it too.
I'll leave the rest to you.

**Comment by carlfriedrich** [comment]
Done with https://github.com/Homebrew/homebrew-core/pull/129392.
