### ISSUE TITLE
Feature request: Support for git commit -m

### ISSUE THREAD

**Issue by obvionaoe** [wfxr/forgit#198]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Feature
Hi, is it possible to add support for the `git commit` command? So, an interactive `git commit` message editor, basically!

Thanks

**Comment by cjappl** [comment]
Hi Luís,

Would you go into detail about what you’d want to see with this command?

Most of the forgit commands show either the git tree, or files that need to be added or diffed in some way.

The commit command, with the m flag is just a simple command that doesn’t really show any state.

If you elaborate on your idea a bit we can think about if we want it!

Also always open to PRs if you want to contribute.

**Comment by obvionaoe** [comment]
Hi, sorry for the late reply, I was thinking something like this:

![commit.jpg](https://user-images.githubusercontent.com/35278323/166436246-8f706a50-d2f2-44b7-a36b-66e934a663a6.jpg)

Where you would be able to see the files you are commiting and the changes being made, so that you could type up the commit message in the top box based on what was shown on the diff

**Comment by cjappl** [comment]
Assigning to @wfxr for comments/thoughts

**Comment by wfxr** [comment]
> so that you could type up the commit message in the top box based on what was shown on the diff

Search bar of fzf is for filtering inputs (items in the left side), not for text editing. You can just run `git status -s` or `gd HEAD` to check the changes before writing the commmit message `git commit -m "..."`.
