### ISSUE TITLE
XDG default folder

### ISSUE THREAD

**Issue by quintrino** [wfxr/forgit#20]
https://github.com/wfxr/forgit/blob/3c7b9ea4b81d0b6de31a177b536ba807aace8cd2/forgit.plugin.zsh#L86

Could we change this so that it will use $XDG_CONFIG_HOME if it's set and otherwise use the home directory?

Thanks for a great program!

**Comment by wfxr** [comment]
Sorry for the late reply. 
I hava made a little change.Now `forgit` can use user's custom gitignore templates repo and specified where to put the repo as well.
For your case. Just export `FORGIT_GI_REPO_LOCAL` variable before the `forgit` loaded.
