### ISSUE TITLE
Diffs for Python files have somewhat nonsensical headings if they are at the module level namespace

### ISSUE THREAD

**Issue by taranlu-houzz** [wfxr/forgit#202]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce
If there are changes that occur outside of a function or class, the "Header" that `forgit` choses for that particular diff chunk is often confusingly unrelated to the diff content. For example, the "Header" might be a random `import` line:
![Screen Shot 2022-05-18 at 02 07 00](https://user-images.githubusercontent.com/52425255/169002391-4cf45d42-49c1-4ed2-8f22-ce461afe2965.png)

It seems like maybe it would be better to just have a catchall term used for module level changes?

**Comment by wfxr** [comment]
@taranlu-houzz forgit has nothing to do with the diff content. It's provided by [delta](https://github.com/dandavison/delta). Maybe You should probably ask on delta's repo.

**Comment by taranlu-houzz** [comment]
@wfxr Ah, right, of course. Sorry about that. I will ask on their repo. I forgot that I had installed `delta` to test it out a while back. Thank you for letting me know.
