### ISSUE TITLE
`gd` does not show diff in preview

### ISSUE THREAD

**Issue by taranlu-houzz** [wfxr/forgit#203]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce
When I try to use `gd` in my project repo, `fzf` pops up correctly and shows the modified file, but the preview is blank. The change is not staged, and when I use `ga` the preview does show the change correctly.

I also tried this in a clone of the `forgit` repo, and in that case, both `gd` and `ga` worked as expected.

I guess there must be something different about the config in my project repo, but I am unsure what that would be...

**Comment by wfxr** [comment]
@taranlu-houzz @tvenable-mie Thanks for your report! I make the pr #204 to fix this. Can you update and help test it?

**Comment by tvenable-mie** [comment]
@wfxr That PR fixes it for me. Thanks!

**Comment by cjappl** [comment]
Closing, opened a similar issue for fish for me to fix! Thanks for the help @taranlu-houzz @tvenable-mie
