### ISSUE TITLE
Parse error after new installation

### ISSUE THREAD

**Issue by lastcoolnameleft** [wfxr/forgit#205]
## Check list

- [ X ] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [ X ] I have the latest version of forgit
- [ X ] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [ X ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ X ] zsh
    - [ ] fish

## Problem / Steps to reproduce

My scenario:
* Install `fzf` via Brew
* Cloned `forgit` repo and source via `. ~/git/tmp/forgit/forgit.plugin.zsh`
* Run `glo` and get error in right-side window:
```
zsh:1: parse error near `|`
```

**Comment by cjappl** [comment]
Assigning to @wfxr

**Comment by rablador** [comment]
Having the same setup and same error.

**Comment by cjappl** [comment]
If anyone has time to put together a PR for this one I’d love the help! I can’t repro on my side because my shell and $SHELL match.

I’m partially inclined to think this is kind of “undefined behavior” of a sort, but if we can find a fix that works for both versions and is sturdy to new features I’m happy to merge it!

**Comment by dykwok** [comment]
@lastcoolnameleft , @cjappl you can check your .gitconfig settings, and remove the "pager" setting. It works for me. 
@wfxr  Could you adapt the pager setting automatically?

**Comment by rablador** [comment]
Still same problem for me :/

**Comment by cjappl** [comment]
@carlfriedrich any ideas here?

**Comment by carlfriedrich** [comment]
No concrete idea, but @lastcoolnameleft @rablador can you maybe checkout [my branch](https://github.com/carlfriedrich/forgit/tree/move-implementation-to-standalone-forgit) from #241 and see if the error appears there as well?

**Comment by rablador** [comment]
Running `git forgit` from the branch "move-implementation-to-standalone-forgit", with PATH pointing to the bin folder yields:

git-forgit: line 526: _forgit_: command not found

**Comment by carlfriedrich** [comment]
@rablador Thanks for your feedback. What was the exact command that you tried? `git forgit` alone doesn't do anything, since we need to provide a forgit subcommand like `git forgit log`.
But nevertheless `git forgit` alone should provide a useful error message, I will add a patch for that.

**Comment by rablador** [comment]
Ah, right, I forgot to add a command! It works! :D

**Comment by carlfriedrich** [comment]
@rablador Great, so the error from this issue is gone on the new branch? We will merge this in the next few days, so then the issue should be solved in `master` as well.

@rablador What about you, can you verify this in your environment?

**Comment by carlfriedrich** [comment]
@rablador Great, so the error from this issue is gone on the new branch? We will merge this in the next few days, so then the issue should be solved in `master` as well.

@lastcoolnameleft What about you, can you verify this in your environment?

**Comment by rablador** [comment]
@carlfriedrich Yeah, from the branch "move-implementation-to-standalone-forgit" everything works as expected as long as I supply a command for `git forgit`. :)

**Comment by carlfriedrich** [comment]
@rablador Great, thank you. I already added a commit to the branch which displays a useful error message if no or an invalid command is given, so that shouldn't be a problem anymore either. :-)

**Comment by carlfriedrich** [comment]
#241 has been merged, so after the feedback from @rablador I am considering this fixed. If anyone still has this problem, please open a new issue.
