### ISSUE TITLE
Fish bug: some of the commands (glo, gss) don't work

### ISSUE THREAD

**Issue by radiden** [wfxr/forgit#208]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

Run `glo` or `gss` in fish. Instead of getting fzf the shell hangs, after pressing random buttons the cursor disappears, until Ctrl+C is hit. Other commands seem to work fine.

Versions:
```
git version 2.36.0
fzf 0.30.0 (tarball)
fish, version 3.4.1
```

**Comment by endigma** [comment]
can reproduce void linux & nix latest

**Comment by cjappl** [comment]
Hi @endigma ,

Thanks for the report!! Unfortunately I don't have a linux box to test and fix with, is there any way you could submit a PR if you get to the bottom of it? 

On my OSX machine, these commands are working as intended. (see screenshots below)

```
$ git --version
git version 2.34.1
$ fish --version
fish, version 3.1.2
$ fzf --version
0.25.1 (brew)
```

glo:
<img width="1438" alt="Screen Shot 2022-05-30 at 11 27 19 AM" src="https://user-images.githubusercontent.com/14171107/171044822-31057149-065c-49b3-a45a-687603caf681.png">

gss:
<img width="1438" alt="Screen Shot 2022-05-30 at 11 28 58 AM" src="https://user-images.githubusercontent.com/14171107/171044868-82080944-9891-4aef-a9b3-503ce4067010.png">

**Comment by endigma** [comment]
you should try https://github.com/lima-vm/lima

**Comment by jgoldhammer** [comment]
I can reproduce that glo hangs under macos.
I am using following versions:
```
fzf --version
0.30.0 (brew)

fish --version
fish, version 3.5.0

git --version
git version 2.36.1
```

**Comment by cjappl** [comment]
I would fully support a PR to help fix this! Unfortunately I can't repro so I am not of help. If anyone wants to step up, happy to help review 😄

**Comment by goncharov** [comment]
I faced the same issue after installation of [oh-my-fish/plugin-grc](https://github.com/oh-my-fish/plugin-grc). It overrides `env` command. As workaround I've excluded `env` to override by `set -U grc_plugin_ignore_execs env`

**Comment by endigma** [comment]
> I faced the same issue after installation of [oh-my-fish/plugin-grc](https://github.com/oh-my-fish/plugin-grc). It overrides `env` command. As workaround I've excluded `env` to override by `set -U grc_plugin_ignore_execs env`

This is the fix.
