### ISSUE TITLE
Support for options to pass to `git diff`

### ISSUE THREAD

**Issue by jamadagni** [wfxr/forgit#21]
Hello and thank you for `forgit`. I think I am starting to like it.

But I didn't find `diff-so-fancy` (which you suggest in the README) to my particular liking so I removed it.

My `git df` alias uses `-w` to suppress white space changes to increase the content-wise SNR, and `--word-diff=color` to avoid excess lines in my diffs. I would like `ga` to show the same. Likewise others may have other diff preferences.

`ga` needn't do anything specific to support each option, but if you provide some mechanism to pass our desired options to `git diff`, such as from an environment variable `FORGIT_DIFF_OPTIONS` (similar to existing `FORGIT_FZF_DEFAULT_OPTS`) then it would be useful.

Thanks!

**Comment by wfxr** [comment]
@jamadagni Thanks for @doronbehar 's work. Now you can custom the preview behavior by setting the command-specified fzf options(like `FORGIT_DIFF_FZF_OPTS`).
