### ISSUE TITLE
Add installation line for Oh my zsh

### ISSUE THREAD

**Issue by anarchy89** [wfxr/forgit#212]
## Check list

- [ x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x ] I have the latest version of forgit
- [ x] I have searched through the existing issues

## Environment info

- OS
    - [x ] Linux
    - [x ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ x] zsh
    - [ ] fish

## Problem / Steps to reproduce

add installation line for oh my zsh,

git clone https://github.com/wfxr/forgit.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/forgit

**Comment by carlfriedrich** [comment]
Done with #212.
