### ISSUE TITLE
glo and ga incorrectly display terminal color codes

### ISSUE THREAD

**Issue by phillipreeder** [wfxr/forgit#214]
## Check list

- [X] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [X] I have the latest version of forgit
- [X] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

## Problem / Steps to reproduce
Using fzf 0.30.0 and forgit 98a5cc2 displays terminal color codes instead of actually rendering the colors for the `glo` and `ga` commands. This prevents the commit from loading correctly in preview.
<img width="928" alt="Screen Shot 2022-07-08 at 2 21 11 PM" src="https://user-images.githubusercontent.com/100375973/178072592-d112c780-ee6d-415a-bd0c-584c6feb76ae.png">

**Comment by wfxr** [comment]
@phillipreeder Can you update forgit and try again? I cannot repro:
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/6105425/179441209-91bcff0f-3514-461b-8705-d51f9de831cd.png">

**Comment by wfxr** [comment]
@phillipreeder Can you run the following command to see if fzf is working properly?

```sh
echo -e "\e[32mRed text\e[0m" | fzf --ansi
```

**Comment by phillipreeder** [comment]
Output of 32m and 31m

<img width="455" alt="Screen Shot 2022-07-20 at 8 50 50 AM" src="https://user-images.githubusercontent.com/100375973/180026982-0a026ebb-f5a1-4c46-8d5e-ca8005abfb2a.png">
<img width="455" alt="Screen Shot 2022-07-20 at 8 52 34 AM" src="https://user-images.githubusercontent.com/100375973/180027281-ed296002-894a-41bf-8c4d-cac835712300.png">

**Comment by wfxr** [comment]
Weird...fzf seems ok to render ansi color. Have you modified the `--ansi` option for `fzf`?

https://github.com/wfxr/forgit/blob/bd8fce74a662fd6ed90d942a797531ffd0492ae8/forgit.plugin.zsh#L416

**Comment by phillipreeder** [comment]
```
~ ❯ echo $FZF_DEFAULT_OPTS
--layout=reverse
~ ❯ echo $FORGIT_FZF_DEFAULT_OPTS
--exact --border --cycle --reverse --height '80%'
```

**Comment by phillipreeder** [comment]
That did the trick, moving configs to before sourcing forgit solved the issue. Thanks!
