### ISSUE TITLE
[Fish] ga/gd no longer works after plugin upgrade 

### ISSUE THREAD

**Issue by ray-x** [wfxr/forgit#224]
## Check list

- [X] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [X] I have the latest version of forgit
- [X] I have searched through the existing issues

## Environment info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [X] fish

## Problem / Steps to reproduce
in a git repo, run `ga` or `gd`
The script complains about forgit::extract_file  not found/syntax error.

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/1681295/181606096-55961de2-fe64-4ff7-a353-7e5199e2e42b.png">

Update:  my $SHELL is set to `bash`, but my current shell is `fish`, set $SHELL to `fish` works fine. 
Similar to this https://github.com/wfxr/forgit/issues/168

**Comment by cjappl** [comment]
hmm, this is interesting.

Is there a reason that your $SHELL is bash instead of fish?

See also this ticket: https://github.com/wfxr/forgit/pull/169

There was a fix for it then, but it broke mine when my $SHELL was fish...

**Comment by cjappl** [comment]
I'm not sure there is a long term solution that will fix both, as fish syntax is very different than bash syntax, and we rely on fish scripting internally to have it work properly

**Comment by ray-x** [comment]
If login shell is fish, I think it should be OK.  But if you switch between shells, might be an issue.

**Comment by ray-x** [comment]
as there is a workaround, close it for now.
