### ISSUE TITLE
Right interactive panel with changes not shown when glo inside tmux

### ISSUE THREAD

**Issue by carmilso** [wfxr/forgit#227]
## Check list

- [X] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [X] I have the latest version of forgit
- [X] I have searched through the existing issues

## Environment info

- OS
    - [X] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

## Problem / Steps to reproduce

Hi all,

I'm facing a minor issue that I would like to fix. The thing is that when I use `forgit` inside `tmux`, then I don't see the interactive panel at right that shows changes when you select the commits from the left when you do a `glo`.

So if I am not in `tmux` then it shows the two panels: at left you can see the history of commits and at right you can see the changes. But for some reason this is not the behaviour when you do it inside `tmux`. So inside `tmux` I need to <Intro> on every commit to see the changes.

This is my `forgit` configuration:
```
export FORGIT_FZF_DEFAULT_OPTS="$FORGIT_FZF_DEFAULT_OPTS
--reverse
--exact
--border
--cycle
--height '90%'
"
```

Any idea about this?

**Comment by carlfriedrich** [comment]
@carmilso This should usually work (and works in my case). Does running a plain `fzf` show a preview window for you in both scenarios?

```
fzf --preview "cat {}"
```

Do you have [`fzf-tmux`](https://github.com/junegunn/fzf#fzf-tmux-script) installed?

**Comment by carmilso** [comment]
@carlfriedrich this is what I tried:

```
fzf --preview "cat {}"
```

That command gives me the following error output:
![image](https://user-images.githubusercontent.com/7313231/196614706-3458d1d9-48f0-4217-9c9a-368178c8697d.png)

On the other hand, `fzf-tmux` is installed since I can run it.

So this is the output outside tmux:

![image](https://user-images.githubusercontent.com/7313231/196615594-138059ec-d7e0-4f56-941c-5930c07f65bd.png)

And this is the output when I'm inside tmux (where you need to enter into each file changed to see changes):

![image](https://user-images.githubusercontent.com/7313231/196615702-a6451bf7-a676-4864-9e48-834287178718.png)

**Comment by carlfriedrich** [comment]
Strange that your plain `fzf` command does not work. How does this behave?

```
find | fzf --preview "cat {}"
```

**Comment by carmilso** [comment]
> Strange that your plain `fzf` command does not work. How does this behave?
> 
> ```
> find | fzf --preview "cat {}"
> ```

Yes, I think the same. That one works as expected:
![image](https://user-images.githubusercontent.com/7313231/196618470-fce153d5-3af2-4511-9703-5052c005af8e.png)

**Comment by carlfriedrich** [comment]
I don't see a preview, though. So does it behave identically to forgit (preview without tmux, no preview with tmux)? If that's the case, then this is not a forgit problem but a fzf problem and you should file an issue [over there](https://github.com/junegunn/fzf).

**Comment by carmilso** [comment]
> I don't see a preview, though. So does it behave identically to forgit (preview without tmux, no preview with tmux)? If that's the case, then this is not a forgit problem but a fzf problem and you should file an issue [over there](https://github.com/junegunn/fzf).

Well, the preview is what you see below the `~ < 43/43 (0)`. So if I write for example `index` it will only show `./git/index` as expected. It behaves the same in tmux and outside tmux:
![image](https://user-images.githubusercontent.com/7313231/196620338-542bf53f-9f84-4f61-97a5-a4889f105050.png)

**Comment by carlfriedrich** [comment]
No, that's not the preview, it's the finder area. The preview window should show the file contents (that's what the preview command `cat {}` does):

![grafik](https://user-images.githubusercontent.com/45259958/196623290-74fe056a-34da-44ce-a83e-6270aaad3a5a.png)

**Comment by carmilso** [comment]
> No, that's not the preview, it's the finder area. The preview window should show the file contents (that's what the preview command `cat {}` does):
> 
> ![grafik](https://user-images.githubusercontent.com/45259958/196623290-74fe056a-34da-44ce-a83e-6270aaad3a5a.png)

Okay, it was because a bad configuration of fzf options the reason why that `find | fzf --preview "cat {}"` was not working. But it's curious because now it works from outside tmux but not from inside (it gives the same error as before) so as you say I assume it is some fzf misconfiguration with tmux and not forgit itself. I will investigate that.

Thanks for helping!
