### ISSUE TITLE
Resize left pannel in glo

### ISSUE THREAD

**Issue by pookdeveloper** [wfxr/forgit#229]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Any way to resize the leftside pannel in **glo**

![image](https://user-images.githubusercontent.com/3384734/183245634-9317f7a3-e123-47a8-81f8-ffe8b6074345.png)

**Comment by cjappl** [comment]
Hmm, great question. Maybe  @wfxr knows.

I would ask in the `fzf` repo, as this is basically just a look at that tool. You can then pass that option into our commands by setting or adding to `FORGIT_FZF_DEFAULT_OPTS`

**Comment by wfxr** [comment]
@pookdeveloper I think you cannot resize the left part, but you can achieve the same goal through resizing the preview window using `--preview-window` option provided by fzf.

**Comment by cjappl** [comment]
Going to close unless we hear a response soon.

**Comment by cjappl** [comment]
Closing - stale
