### ISSUE TITLE
Why do you use incompatible :: in functions' names

### ISSUE THREAD

**Issue by doronbehar** [wfxr/forgit#23]
As the title of this issue suggests, I noticed that functions named `forgit::fzf` for example can't be used in `/bin/sh`:

```
sh-5.0$ forgit::fzf () {
> echo hello
> }
sh: `forgit::fzf': not a valid identifier
sh-5.0$
```

I know that in the past you've had 2 files for Bash/sh and for ZSH and that some-when you've made them symlinks. I agree that having just a single file is better but why use functions with names such as these and not use underscores?

I could send a patch to fix this but I wanted to ask first.

As once mentioned in a previous [discussion we've had](https://github.com/wfxr/forgit/pull/12#issuecomment-437085251), This really bothers me because I use forgit in Git's shell aliases as explained in the linked comment from #12 . From some reason Git is also giving me the error `not a valid identifier` when I try to use forgit with it's shell aliases.

**Comment by wfxr** [comment]
In fact there is no special reason I have to name it like `forgit::fzf`. But compared to snake style this name pattern is kind of showing namespace concept.

Which shell do you use? I have had tested it's ok both in `bash` and `zsh`.

**Comment by doronbehar** [comment]
As I said, it doens't work with `/bin/sh`. I assume this is the shell that Git uses although my `$SHELL` is `/bin/zsh`.

**Comment by wfxr** [comment]
@doronbehar Maintaining compatibility for `sh` is a very troublesome thing but few people would choose `sh` as their login shell.

What you said is right that git use `/bin/sh` to execute external commands. But it doesn't prevent you choosing another shell. In fact the following lines should work as you expected:
```toml
[alias]
flog = "!bash -c 'source path/to/forgit.plugin.sh && forgit::log $@'"
```

**Comment by doronbehar** [comment]
Thanks, I'm aware of this workaround but I hope it can be avoided. I tested all of the functions under `/bin/sh` with the only change of the functions renamed with underscores and I haven't noticed any difference in behaviour, which means everything else seems compatible.

I hope you'll consider this proposal. I can send a PR right away if you wish.

**Comment by wfxr** [comment]
Thanks for your suggestion. But make a promise for `sh` compatibility is still a burden. What if someday we want to add some awesome features but the old `sh` does not support? Split the source to two versions again? Or write some dirty workaround code and mix them into the single file? 

Take a step back and say I keep the plugin compatibility with `sh`. But how about `fish`, `ksh`, `chsh`(or even `PowerShell` on windows)?

We can do it but not means we should do it. Almost nobody will use `sh` as their login shell. That's not a feature we have to implement. 

**Entities should not be multiplied unnecessarily.**
