### ISSUE TITLE
Preview a single file diff

### ISSUE THREAD

**Issue by nkh** [wfxr/forgit#242]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

running `fgl -- some/file` displays all the commit where some/file was somewhat involved. `git log -p some/file` displays the diff for that file only but `fgl -p some/file` puts the diff in the list of commit rather than showing only that file's diff.

**Comment by carlfriedrich** [comment]
I can reproduce this:

![grafik](https://user-images.githubusercontent.com/45259958/196618311-3fc16a45-1e28-4f53-b325-40459712b2e7.png)

If `fgl -- some/file` works, though, why do you need `fgl -p some/file` to work?

I'm not sure if we actually support optional git command line arguments on forgit. @wfxr @cjappl Do we?

**Comment by wfxr** [comment]
@carlfriedrich Sadly not.

https://github.com/wfxr/forgit/blob/2872548075e63bc83a0b960e2813b16571998563/forgit.plugin.zsh#L37-L42

**Comment by nkh** [comment]
@carlfriedrich I'd need it so i can go from one commit to the other and see the diff for just that commit

**Comment by carlfriedrich** [comment]
@nkh But that already works with `fgl -- some/file` as you said?

**Comment by nkh** [comment]
it was part of a script that used git options, now I have the answer, I'll see if it can be changed.
