### ISSUE TITLE
Git stash interactive

### ISSUE THREAD

**Issue by clenemt** [wfxr/forgit#243]
## Check list

- [X] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [X] I have the latest version of forgit
- [X] I have searched through the existing issues

## Environment info

- OS
    - [X] Linux
    - [X] Mac OS X
    - [X] Windows
    - [X] Others:
- Shell
    - [X] bash
    - [X] zsh
    - [X] fish

## Problem / Steps to reproduce

More of a feature request then an issue. Does it make sense to have an interactive stash?
I can of course interactively add the things i don't want in my stash, `stash save --keep-index` then reset everything.
Just wondering if other had that need? Could not find anything in the current open/closed issues

**Comment by carlfriedrich** [comment]
@clenemt Thanks for the request. That would definitely make sense and I actually considered it as well in the past already. Would you be willing to come up with a PR?
