### ISSUE TITLE
grh only works correctly when in the root directory

### ISSUE THREAD

**Issue by cjappl** [wfxr/forgit#254]
- Fish Shell
- OSX

Steps to repro
* Change a file 
* git add the file
* `mkdir somesubdirectory && cd somesubdirectory`
* `grh`

Expected:
* File show up in forgit, if you tab select them they get unstaged

Observed:
`Nothing to unstage.`

I think this is a regression with the big merge, if that gives a hint on how to fix it! (not blaming, just pointing that out as a detail that can help track down the fix)

I'll submit a fix for this if I have time :)

**Comment by sandr01d** [comment]
I think this has to do with the `--relative` here:

 https://github.com/wfxr/forgit/blob/42c8e005fece723de68d78906bb3ba7b70ff65c7/bin/git-forgit#L184

Removing this does open the fzf selection, but it doesn't fix this completely as unstaging still doesn't work outside the root directory. I don't have the time to go after this today, but I thought I'd drop a hint.
