### ISSUE TITLE
Feature request: branches

### ISSUE THREAD

**Issue by marcobiedermann** [wfxr/forgit#26]
First of all thank you very much for providing this plugin. Super useful!

It would also be great to include an interactive branch selection.

For example: expect `gbr` to interactively search through all branches.

**Comment by wfxr** [comment]
Thanks for your suggestion.

Have you tried the git completion plugin? I think that would be more appropriate to use the completion mechanism to do this.

Here is the git's completion file from its official repository:
https://github.com/git/git/tree/master/contrib/completion
And its usage:
https://apple.stackexchange.com/questions/55875/git-auto-complete-for-branches-at-the-command-line

`oh-my-zsh` has a more powerful completion named `git-extras`. If you use `oh-my-zsh` or some plugin manager like `zplug` you can activate it easily:

```zsh
zplug "plugins/git-extras", from:oh-my-zsh
```

If you really like the fuzzy completions from `fzf` you can simply add an alias to your `rc` file:
```zsh
alias gco='git checkout $(git branch | fzf | tr -d "*")'
```

**Comment by marcobiedermann** [comment]
@wfxr 

Thank you very much for your response and possible solution.
I already figured out a way how to set it up by myself but wouldn't be nicer to include it into this package to avoid manual setup for each user?
When you break it down `forgit` is also just utility set for `git` functions in combination with `fzf`. So instead of setting up an alias you could also shit it, no?

**Comment by rockandska** [comment]
@marcobiedermann, from a pure completion side, I create a little project named [fzf-obc](https://fzf-obc.readthedocs.io) who add fzf over all completion scripts. Give it a try and open an issue on fzf-obc github if needed.

Regards,
