### ISSUE TITLE
zplug: forgit is not available

### ISSUE THREAD

**Issue by jeusdi** [wfxr/forgit#265]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I've recorded this [asciinema here](https://asciinema.org/a/UR8Ri3FlpGbIfFYsj3MXllxgs) in order to see behavior.
I'm using `zplug`, but I don't quite figure out why `forgit` is not available...

**Comment by carlfriedrich** [comment]
There is no plain command `forgit`. You have to use it either via the [git subcommand](https://github.com/wfxr/forgit#git) `git forgit` or via the [shell aliases](https://github.com/wfxr/forgit#shell-aliases), like described in the documentation.

**Comment by jeusdi** [comment]
Ohhh... I'm really a newbie. I don0t quite figure out which is the magic behind.
I mean, hw is possible that adding a directory on PATH, `git` picks them as subcomands?
I neither understand `aliases` tweaks.
Some ideas in order to understand it?

**Comment by carlfriedrich** [comment]
That's a feature of git:

https://github.com/git/git/blob/master/Documentation/howto/new-command.txt#L15-L22

See the git documentation on aliases:

https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases
