### ISSUE TITLE
Fisher install doesn't work (probably due to the symlink to the main git-forgit script)

### ISSUE THREAD

**Issue by viktomas** [wfxr/forgit#269]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish `3.5.1` with `fisher` `4.4.2`

## Problem / Steps to reproduce

When I install the plugin with `fisher install wfxr/forgit`, fisher creates a symlink to non-existing file

```sh
la ~/.config/fish/conf.d/bin/git-forgit
lrwxr-xr-x 20 tomas 27 Dec 07:38 /Users/tomas/.config/fish/conf.d/bin/git-forgit -> ../../bin/git-forgit
```

(`~/.config/fish/conf.d/bin/git-forgit` points to `../../bin/git-forgit` That is a valid file in this repository, but when installed through `fisher`, the executable `git-forgit` script doesn't get copied and the `../../bin/git-forgit` symlink is broken)

I think that that the issue has been introduced with: https://github.com/wfxr/forgit/commit/4995c614e484a5a4636ffcea6e949dd7bd80bdac

**Comment by carlfriedrich** [comment]
Forgit needs fisher v4.2.3 for this to work, as stated in the documentation:

https://github.com/wfxr/forgit/tree/22.12.0#-installation

Please update fisher before updating forgit.

I will add this information to the release notes of 22.12.0 as well.

**Comment by viktomas** [comment]
Thank you @carlfriedrich 🙇 That's my bad for not reading the instructions carefully enough. Upgrading `fisher` to `4.4.3` fixed the issue. I'm closing this issue.

*(sidenote: in your comment you made a typo in the version: `4.2.3` instead of `4.4.3` but the README docs are correct 👍  Thanks again)*

**Comment by carlfriedrich** [comment]
@viktomas Thanks for the hint, corrected it! 🤗
