### ISSUE TITLE
Feature request: support diff origin

### ISSUE THREAD

**Issue by noboruma** [wfxr/forgit#27]
Hello there,

Could we have support for the `git diff origin` command?
Something like `gd origin` would be perfect.

Motivation:
`git diff` will only show the difference between what was committed and what is **not** committed.
When working with different branches, it is common workflow to commit locally, thus `git diff` will show no difference.

**Comment by wfxr** [comment]
@noboruma Thanks for your suggestion. I like this feature. Will be added later.

**Comment by wfxr** [comment]
@noboruma Implemented.  Now `gd` support the following usages.

```bash
gd v1.0
gd origin
gd f2d6f23
gd README.md
gd master README.md
gd HEAD~ src tests scripts
```

You can try it and check if it works as expected.

**Comment by noboruma** [comment]
This is working great!
Thanks for considering & implementing a solution that quickly!
