### ISSUE TITLE
What theme is used in the Readme.md screenshots?

### ISSUE THREAD

**Issue by Moulick** [wfxr/forgit#28]
The theme used in the pics in the readme.md is sweet. Can I please get the name or a export of  the colour scheme or something?

**Comment by Moulick** [comment]
@wfxr

**Comment by wfxr** [comment]
@Moulick 
Which theme do you mean? (tmux or zsh ?)

**Comment by Moulick** [comment]
I meant the colour scheme here
![image](https://user-images.githubusercontent.com/15780903/62441901-988cd800-b773-11e9-8b18-b33201fa2576.png)

**Comment by wfxr** [comment]
……That's a lot of different components from your description,  include tmux(tmux-power), zsh(spaceship-prompt), ls(exa), git(diff-so-fancy).

Here is my [dotfiles](https://github.com/wfxr/dotfiles). Be patient and you will find all the configurations.
