### ISSUE TITLE
[feature request] copy git stash ID on ctrl+y

### ISSUE THREAD

**Issue by iloveitaly** [wfxr/forgit#287]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

It would be great if you could `cntrl+y` to copy the git stash id when using `gss`

**Comment by carlfriedrich** [comment]
Hi @iloveitaly, thanks for your request.

FYI: You can actually configure this yourself using forgit's [fzf options](https://github.com/wfxr/forgit#fzf-options):

```shell
export FORGIT_STASH_FZF_OPTS="--bind=\"ctrl-y:execute-silent(echo {} | cut -d: -f1 | tr -d '[:space:]' | pbcopy)\""
```

However, I find this a useful addition as we have the same behavior for the SHA in `glo`, so I will file a PR for this.

**Comment by carlfriedrich** [comment]
@iloveitaly Can you verify if #295 works for you?

**Comment by iloveitaly** [comment]
@carlfriedrich Yes! This works for me! Thank you.
