### ISSUE TITLE
Forgit interactive not work on alacritty + tmux 

### ISSUE THREAD

**Issue by vqcuong** [wfxr/forgit#288]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
Hi, I'm try to setup and use forgit but I can make it work on my terminal environment (combo alacritty + tmux + oh my zsh), after install fig and integrate it with alacritty, the issue still remain. May I got some plugins conflicting on my zshrc or because I'm using alacritty. Here is list of enabled plugins I using.
plugins=(
  aws
  colorize
  docker
  docker-compose
  fzf-tab
  fd
  forgit
  fuzzy-emoji
  fzf
  git
  gcloud
  golang
  history
  isodate
  kubectl
  kube-ps1
  macos
  oh-my-matrix
  python
  sudo
  terraform
  tmux
  vundle
  vscode
  zsh-autosuggestions
  fast-syntax-highlighting
)

**Comment by carlfriedrich** [comment]
So what happens when you run forgit?

**Comment by vqcuong** [comment]
thank for help me. I've found problem in my setup.
