### ISSUE TITLE
Diff doesn't work in subdirectories

### ISSUE THREAD

**Issue by Gerrit-K** [wfxr/forgit#29]
# Description
When I have changes in a sub-subdirectory, switch into the intermediate subdirectory and run `gd`, the diff preview from diff-so-fancy is empty (see screenshots below). The files are listed, but the paths are probably incorrect. Notice that although I've `cd`'ed into the subdirectory, the files listed in fzf still have the path related to the git root. Not sure though, if this is an issue with forgit or diff-so-fancy.

# View from the root directory:
![image](https://user-images.githubusercontent.com/8766565/62602929-22b07a00-b8f5-11e9-8da4-cb8064cc3a1b.png)

# View from the subdirectory:
![image](https://user-images.githubusercontent.com/8766565/62602963-352ab380-b8f5-11e9-8619-c9e09bde7069.png)

**Comment by wfxr** [comment]
@Gerrit-K Fixed.

**Comment by Gerrit-K** [comment]
@wfxr Thank ***you*** for the incredibly quick fix!
