### ISSUE TITLE
Feature Request: GCB autocomplete for zsh

### ISSUE THREAD

**Issue by deekshithanand** [wfxr/forgit#291]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce
Is it possible to get a autocomplete of git branches (upon pressing tab) like oh-my-zsh git plugin for aliases `gco` and `gcb` ? or any workaround that can be done?

I tried to source bash autocompletion, but it didnt work and gave an error.

**Comment by carlfriedrich** [comment]
Right now we have completions for [bash](https://github.com/wfxr/forgit/blob/master/completions/git-forgit.bash) and [fish](https://github.com/wfxr/forgit/pull/231) only. Contributions for adding zsh completions are very welcome!
