### ISSUE TITLE
`ga` does not seem to work or load anything

### ISSUE THREAD

**Issue by tdeekens** [wfxr/forgit#3]
First, thanks for this awesome tool! I just discovered it and already wished to have used it for the past months!

However the `ga` which is correctly setup as `which ga` shows that it's the `forgit` function does not trigger/show anything. It seems to either return or swallow an error.

Any idea on if that's a problem with `ga` itself or how I can debug more?

Thanks!

**Comment by wfxr** [comment]
Kind of weird. I have never encountered this issue. Does other command like `glo`, `gd` work for you?
Maybe you run the `ga` on a clean working tree, ie, nothing to add. In this situation, `ga` of course will not trigger fzf. If not, what does the command `git status --short` show on your repo?

**Comment by tdeekens** [comment]
All other commands work just fine and I am really enjoying them. ga is run in a not empty working directory. Two machines have the same issue with it, it seems. 

Does it need any specific dependencies. Like version of awk or sed?

**Comment by wfxr** [comment]
> Does it need any specific dependencies. Like version of awk or sed?

I think these are no special requirements on `awk` or `sed`. I tested the plugin on Linux and MacOS.

Can you run `git status --short` in your git repo and paste the output here?

**Comment by tdeekens** [comment]
Sure. 

```bash
» git status --short                                                                                                                                                 tdeekens@x
 M packages/launchdarkly-adapter/modules/adapter/adapter.js
```

This is a small recording of everything.

![screen recording 2018-04-30 at 11 35 am](https://user-images.githubusercontent.com/1877073/39421766-c6ee8768-4c6a-11e8-9458-d85e8bc9e9f4.gif)

I am running `git version 2.17.0`.

**Comment by wfxr** [comment]
'M' with green color means the file has been modified and **already added**. There is no need to add the same file again unless you do some other modification.
To see if `ga` works fine, run `git reset` to callback the add operation. Or just do some modifications on some file(s) in your repo. Run `ga` again.

**Comment by tdeekens** [comment]
Sorry, but I did not stage the changes of the file. It's an existing file which has unstaged changes.

However, the same happens when creating a completely new file:

```bash
git status --short                                                                                      
?? packages/launchdarkly-adapter/modules/adapter/asdsd.js
```

Also here `ga` does not show up.

**Comment by wfxr** [comment]
Strange...Make sure you have some unstaged files and run the following command one by one to see the output disappeared at which step.
```
git -c color.status=always status --short
```
```
git -c color.status=always status --short |
        grep 31m
```
```
git -c color.status=always status --short |
        grep 31m |
        awk '{printf "[%10s]  ", $1; $1=""; print $0}'
```
```
git -c color.status=always status --short |
        grep 31m |
        awk '{printf "[%10s]  ", $1; $1=""; print $0}' |
        wfxr::fzf -e -0 -m --nth 2..,.. \
            --preview="git diff --color=always -- {-1}
```
```
git -c color.status=always status --short |
        grep 31m |
        awk '{printf "[%10s]  ", $1; $1=""; print $0}' |
        wfxr::fzf -e -0 -m --nth 2..,.. \
            --preview="git diff --color=always -- {-1} |
        cut -d] -f2 |
```
```
git -c color.status=always status --short |
        grep 31m |
        awk '{printf "[%10s]  ", $1; $1=""; print $0}' |
        wfxr::fzf -e -0 -m --nth 2..,.. \
            --preview="git diff --color=always -- {-1} |
        cut -d] -f2 |
        sed 's/.* -> //'
```

**Comment by tdeekens** [comment]
Thanks for the detailed commands. I ran them until `[...] awk '{printf "[%10s]  ", $1; $1=""; print $0}'` when I noticed it must be about my color configuration.

```bash
[color "status"]
   added = yellow
   changed = green
   untracked = cyan
```

Sorry about that but I wasn't aware your plugin sniffs the colors. I'll resort to the defaults for now to have things running.

I guess I could tweak the script to sniff correctly, right? Can the script maybe even read color configurations?

**Comment by tdeekens** [comment]
Yeah. Noticed that too just now. I played a little with it but could not get it to work. Thanks for your efforts!

**Comment by tdeekens** [comment]
💃 It works! 🙇 

I don't know however how to solve this more elegantly or if there is any build in bash/zsh things to map things from color names into codes.

**Comment by wfxr** [comment]
Improvement has been done at #15 .
