### ISSUE TITLE
Relative paths for other commands

### ISSUE THREAD

**Issue by Gerrit-K** [wfxr/forgit#30]
Similarly to #29 I noticed that `grh` (git reset head) and `ga` (git add) were also lacking support for relative paths. Since your fix for #29 was easier than I expected, I thought I'll give it a try myself. I'll submit the PR shortly, looking forward to your feedback.

**Comment by wfxr** [comment]
@Gerrit-K Thanks for your contribution.
Both pr are reasonable. But #32 has some conflicts after #31 merged. You can resolve it then it will be merged.

**Comment by Gerrit-K** [comment]
@wfxr Thanks for your feedback. I fixed the conflicts.
