### ISSUE TITLE
`forgit` does not open in a tmux popup window if fzf tmux options are set

### ISSUE THREAD

**Issue by dljsjr** [wfxr/forgit#303]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

I have `FZF_TMUX=1` and `FZF_TMUX_OPTS='-p60%,80%'` set to be `export`ed by my `.zshrc`. When those are set, the built-in FZF helpers like Alt-C, etc. will default to `fzf-tmux` instead of `fzf`. And by setting `-p` with a `tmux` version >= 3.2, it uses the popup windows instead of a split:

![image](https://user-images.githubusercontent.com/444635/236526002-6a443441-4316-41b0-9bd4-72b981460842.png)

I don't know for sure what the root cause is here, but I'm _**guessing**_ what's happening here is that `forgit` is hardcoded to use the `fzf` binary. It might be nice if `forgit` could detect `FZF_TMUX` or `FZF_TMUX_OPTS`, and if they're set it could behave like the built-in forgit extensions and default to `fzf-tmux`. This should be safe to do universally, as the fzf [README](https://github.com/junegunn/fzf#fzf-tmux-script) states that `fzf-tmux` is smart enough to be well behaved if invoked outside of a `tmux` session:

> It will still work even when you're not on tmux, silently ignoring -[pudlr] options, so you can invariably use fzf-tmux in your scripts.

**Comment by peikk0** [comment]
With `fzf` v0.53.0+ `export FORGIT_FZF_DEFAULT_OPTS='--tmux'` just works now.

**Comment by sandr01d** [comment]
Nice! Can confirm this is working, thanks @peikk0. @dljsjr do you think we should go ahead and close this issue?

**Comment by dljsjr** [comment]
I can confirm that this is now working!
