### ISSUE TITLE
Discussion: The AUR packages have been orphaned

### ISSUE THREAD

**Issue by sandr01d** [wfxr/forgit#311]
Both the [aur/forgit](https://aur.archlinux.org/packages/forgit)  and the [aur/forgit-git](https://aur.archlinux.org/packages/forgit-git) packages in the AUR are currently unmaintained. I'd be willing to step up as a maintainer for these packages but I wanted to check back with you guys first. I think we could use the opportunity to make these packages more official. From my perspective this would include:

* Creating a github action to automatically publish new releases to [aur/forgit](https://aur.archlinux.org/packages/forgit). This should be fairly straight forward as we only have to modify the checksum with `updpkgsums`, update the `pkgver` and set the `pkgrel` to 0 in the PKGBUILD file. And then push it to the AUR using `git`.
* Add the PKGBUILDs of both packages to this repository, so it's easier for people to contribute.
* Install completions with the package and print a message about which files to source in your .zshrc/.bashrc
* Mention the AUR packages in the README as an installation method
* Accept issues with the AUR package in this repository

I'm happy to support this as much as I can, but at least for the github action somebody would need to upload the secrets etc. It would probably also make sense to have one of the members claim the package and own the private keys to the AUR repo.
So what do you guys think? Is that something you'd be up to?

**Comment by carlfriedrich** [comment]
@sandr01d Thanks a lot for taking the initiative on this. That would definitely be a win IMO!

The GitHub actions secrets can only be created by @wfx as the owner of the repository. We have done this before, however, for the automatic monthly releases in #248.

**Comment by carlfriedrich** [comment]
@sandr01d Thanks a lot for taking the initiative on this. That would definitely be a win IMO!

The GitHub actions secrets can only be created by @wfxr as the owner of the repository. We have done this before, however, for the automatic monthly releases in #248.

**Comment by sandr01d** [comment]
> @sandr01d I am also an arch user (https://aur.archlinux.org/account/wfxr). Maybe you can set me up as a co-maintainer so that we can upload and use my aur key?

Perfect, that makes things a lot easier. I've adopted the package and added you as a co-maintainer for both [aur/forgit-git](https://aur.archlinux.org/packages/forgit-git) and [aur/forgit](https://aur.archlinux.org/packages/forgit).

**Comment by sandr01d** [comment]
@wfxr I'll mention you as co-maintainer in the PKGBUILD aswell. Could you let me know under which name and e-mail you want to be mentioned?

**Comment by wfxr** [comment]
> @wfxr I'll mention you as co-maintainer in the PKGBUILD aswell. Could you let me know under which name and e-mail you want to be mentioned?

Wenxuan Zhang <wenxuangm@gmail.com> should be OK.
