### ISSUE TITLE
Feature Request: checkout_branch: Sort by committerdate

### ISSUE THREAD

**Issue by guettli** [wfxr/forgit#334]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

I found `forgit` because I was looking for a convenient way to switch between branches.

Up to now I used:

```
alias gbs="git branch --sort=-committerdate | fzf --header Checkout | tr '*' ' ' | xargs git checkout"
```

But this does not work for remote branches.

I tried `git forgit checkout_branch` but the list of branches seem to be sorted by alphabet, not by committerdate.

It would be great if you could sort that by committerdate.

Related: https://stackoverflow.com/questions/5188320/how-can-i-get-a-list-of-git-branches-ordered-by-most-recent-commit

**Comment by guettli** [comment]
Of course, I could configure it somehow, so that it works for me.

But why not provide it as default?

**Comment by cjappl** [comment]
I think we would have to have a very good reason to break our existing default, just in case others rely on it. I think allowing people to customize what they want it to be allows this functionality.

Anyone else have any thoughts? @carlfriedrich @sandr01d . I'm not totally opposed, my only opposition is breaking the existing default for another valid default without a really good reason to do so.

**Comment by guettli** [comment]
BTW, I use that now:

```bash
#!/bin/bash
# git switch sorted
# Switch to a branch, show branches sorted by last change.
# Related: https://stackoverflow.com/questions/5188320/

branch="$(git for-each-ref --sort=-committerdate refs \
--format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))' \
 | fzf | sed  's/^[ *]*//' | sed 's#origin/##'| cut -d' ' -f1)"
if [ -z "$branch" ]; then
    exit 1
fi
git switch "$branch"
```

Feel free to do what ever you like with my feedback. Feel free to close it.

**Comment by sandr01d** [comment]
> I think we would have to have a very good reason to break our existing default, just in case others rely on it. I think allowing people to customize what they want it to be allows this functionality.
> 
> Anyone else have any thoughts? @carlfriedrich @sandr01d . I'm not totally opposed, my only opposition is breaking the existing default for another valid default without a really good reason to do so.

I think we should follow gits default behavior when we can. This way forgits behavior is predictable for users who are familiar with using git from the command line (probably most of our users). Also, if we do not provide any options to the git command, git follows what is defined in .gitconfig where you can set `branch.sort`. I think being able to control this behavior for both git and forgit at the same place is great.

**Comment by guettli** [comment]
@sandr01d thank you for this hint. I was not aware of that. Now I change my default setting like this:

```
git config --global branch.sort -committerdate
```

This is great, and the overall goal of what I was searching for. Thank you!

**Comment by carlfriedrich** [comment]
I also don't see any reason to change the default behavior. Requests like these are the reason why we have the config env variables in forgit, while @sandr01d 's proposal with the git config is even better in this specific case.

Maybe this is something we could add to the documentation? Otherwise I would say that this issue can be closed.

**Comment by cjappl** [comment]
I think I'll vote for closing for now! If we get a new issue in the future we can consider adding it to the documentation.
