### ISSUE TITLE
`[]` in a file name brakes the preview window

### ISSUE THREAD

**Issue by clenemt** [wfxr/forgit#353]
## Check list

- [X] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [X] I have the latest version of forgit
- [X] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [X] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

* Have a file named `foo/bar/[baz]/buzz.py` in your git repo.
* Use one of the forgit command to get a fzf window
* The `[]` in the file name makes the preview window brake (picture attached).

<img width="1511" alt="image" src="https://github.com/wfxr/forgit/assets/447956/a62d540e-09fb-44ad-a102-dfe7f786989a">

Sadly this is becoming very common file names due to remix/next and other frontend frameworks with file based routing.
https://nextjs.org/docs/pages/building-your-application/routing/dynamic-routes

Thanks 🙇

**Comment by clenemt** [comment]
Amazing! Fast and responsive 🙇 
I will try when the fix is out and let you know asap!

**Comment by sandr01d** [comment]
Alright, thanks. Will be closing this issue for now but please feel free to report back here or reopen it should the issue not be resolved.
