### ISSUE TITLE
[Warn] Config options have to be exported in future versions of forgit.

### ISSUE THREAD

**Issue by Pirols** [wfxr/forgit#359]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Every time I open a terminal, I get the following warning message:

```
[Warn] Config options have to be exported in future versions of forgit.
[Warn] Please update your config accordingly:
[Warn]   export FORGIT_INSTALL_DIR
```

The only relevant line I have in my .zshrc is `source "/usr/share/zsh/plugins/forgit/forgit.plugin.zsh"`.

`set -x | grep FORGIT_ ` shows that no variable is set. It somehow seems that [these lines](https://github.com/wfxr/forgit/blob/master/forgit.plugin.zsh#L20-L21) do not export the variable. Any ideas? :thinking:

**Comment by wfxr** [comment]
I cannot repro this problem. @carlfriedrich Can you help take a look?

**Comment by Pirols** [comment]
> I cannot repro this problem. @carlfriedrich Can you help take a look?

I found the culprit! I was aliasing `grep` to `rg`! A bad idea from younger me. Thanks for taking the time to try to reproduce this.
