### ISSUE TITLE
Add option to customize git log formatting

### ISSUE THREAD

**Issue by oemergenc** [wfxr/forgit#36]
It would be nice to allow customization of git log formatting. Right now this seems to be hard coded in the code.

**Comment by wfxr** [comment]
@oemergenc Thanks for your suggestion. Unfortunately it is difficult to implement because we need grep the commit hash for the diff preview which require the pre-defined log format.

But if you really don't like the log format you can override the `forgit::log` function (about 10 lines as you see).
