### ISSUE TITLE
Feature request: add icdiff support

### ISSUE THREAD

**Issue by stephencheng** [wfxr/forgit#37]
First, this script is so cool.

It would be great it can optionally support icdiff as a side by side viewer.

Essentially the code change would be some thing like: 
   # cmd="git diff --color=always $commit -- {} $forgit_fancy"
to
  # cmd="git icdiff --color=always $commit -- {} 

Thanks

**Comment by wfxr** [comment]
@stephencheng 
Thanks for your suggestion but `icdiff` is not the standard sub command for git. Implement a function which is not in the scope of the standard git is not the project's goal.

If your prefer `icdiff` you can override the `forgit::diff` in your bashrc/zshrc.
