### ISSUE TITLE
git diff fails with bad revision '' on OSX

### ISSUE THREAD

**Issue by keatsfonam** [wfxr/forgit#373]
## Check list

- [X] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [X] I have the latest version of forgit
- [X] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

versions:
```
git version 2.44.0
zsh 5.9 (x86_64-apple-darwin23.0)
```

Commit ab1116da0e11b90bdcd54f33f172d96bc7fbd392 broke git diff for my OSX system:

```
❯ bin/git-forgit diff
fatal: bad revision ''
```

Bad:
```
❯ git checkout ab1116da0e11b90bdcd54f33f172d96bc7fbd392
HEAD is now at ab1116d Refactor: Replace deferred git commands with regular git commands

❯ bin/git-forgit diff
fatal: bad revision ''
```

Previous commit (61db097badc66dd9f7ee78f5ae4731aeb0cba449):
```


❯ git checkout 61db097badc66dd9f7ee78f5ae4731aeb0cba449
Previous HEAD position was ab1116d Refactor: Replace deferred git commands with regular git commands
HEAD is now at 61db097 Refactor: Replace _forgit_emojify deferred code variable with a function
❯ bin/git-forgit diff
 
(no error)
```

Other commands seem to work
I tested with bash `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin23)` and it is also broken

**Comment by sandr01d** [comment]
@cjappl could you take a look, I'm unable to reproduce this on Linux.
@keatsfonam is `$FORGIT_DIFF_GIT_OPTS` set in your environment?

**Comment by keatsfonam** [comment]
FORGIT_DIFF_GIT_OPTS is not set

OSX version is 14.4 (23E214)

**Comment by keatsfonam** [comment]
Issue seems to arise from this line https://github.com/wfxr/forgit/commit/ab1116da0e11b90bdcd54f33f172d96bc7fbd392#diff-e7404556b00c1c7af95effe409a0f05ded287236878c22735194ee0bc0b98d11R231

when the `commits` array is empty it is evaluated differently compared to with the string

```
❯ git diff --name-status $commits --
M       bin/git-forgit


❯ git diff --name-status "${commits[@]}" --
fatal: bad revision ''

```

**Comment by sandr01d** [comment]
> Issue seems to arise from this line [ab1116d#diff-e7404556b00c1c7af95effe409a0f05ded287236878c22735194ee0bc0b98d11R231](https://github.com/wfxr/forgit/commit/ab1116da0e11b90bdcd54f33f172d96bc7fbd392#diff-e7404556b00c1c7af95effe409a0f05ded287236878c22735194ee0bc0b98d11R231)
> 
> when the `commits` array is empty it is evaluated differently compared to with the string
> 
> ```
> # old behavior
> ❯ git diff --name-status $commits --
> M       bin/git-forgit
> 
> 
> # new behavior
> ❯ git diff --name-status "${commits[@]}" --
> fatal: bad revision ''
> ```

Thanks @keatsfonam, very helpful! Does the following work for you or do you receive an error aswell:

```sh
git diff --name-status ${commits:+"${commits[@]}"} --
```

This appears to be an issue with the old bash version that OSX is using:

https://stackoverflow.com/questions/7577052/bash-empty-array-expansion-with-set-u

**Comment by keatsfonam** [comment]
It works:
```
❯ git diff --name-status ${commits:+"${commits[@]}"} --
M       bin/git-forgit
```

FYI I get the same behavior for zsh and bash. I originally ran into this with latest zsh

**Comment by sandr01d** [comment]
> And looks like bash 3.2 is fairly ancient. I tested with ﻿5.2 and master works properly as expected.

It is, unfortunately we can't expect Apple to update Bash any time soon. Probably not at all.

> Ideally it would support OSX out of the box

Absolutely, we're fixing this. I've created #375. Could you give it a try and let me know if it works for you?

**Comment by keatsfonam** [comment]
To reproduce:

```
docker run -it bash:3.2
apk add git fzf
git clone https://github.com/sandr01d/forgit.git -b fix-gd-macos
cd forgit/
...
bash-3.2# bin/git-forgit diff
fatal: bad revision ''
```
