### ISSUE TITLE
Brew installation of fish shell plugin failing 

### ISSUE THREAD

**Issue by Trid-collab** [wfxr/forgit#377]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [ ] I have the latest version of forgit
- [ ] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

I am new to this. Need help. I have installed forgit on my MacBook as per the installation instructions mentioned for both zsh and fish shells using brew 

then pasted the following as mentioned 
#### ~/.config/fish/config.fish:
 [ -f $HOMEBREW_PREFIX/share/forgit/forgit.plugin.fish ]; and source $HOMEBREW_PREFIX/share/forgit/forgit.plugin.fish

#### ~/.zshrc:
 [ -f $HOMEBREW_PREFIX/share/forgit/forgit.plugin.zsh ] && source $HOMEBREW_PREFIX/share/forgit/forgit.plugin.zsh`

However I find that forgit works on my zsh shell but isn't in the fish shell
I get the following error if I run say 'glo' in the fish shell, where as it works on the zsh shell

```shell

``` ↪ git-forgit log
fish: Unknown command: /opt/homebrew/share/conf.d/bin/git-forgit
- (line 1):
function git-forgit --wraps /opt/homebrew/share/conf.d/bin/git-forgit --description 'alias git-forgit /opt/homebrew/share/conf.d/bin/git-forgit';  /opt/homebrew/share/conf.d/bin/git-forgit $argv
                                                                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
in function 'git-forgit' with arguments 'log'

**Comment by sandr01d** [comment]
As you are our fish and macOS guru, could you take a look at @cjappl?

**Comment by cjappl** [comment]
Can you give the output of:

```
> ls $HOMEBREW_PREFIX/share/forgit/forgit.plugin.fish
```

As well as:
```
> ls $HOMEBREW_PREFIX/bin/git-forgit
```

**Comment by Trid-collab** [comment]
`↪` > ls $HOMEBREW_PREFIX/share/forgit/forgit.plugin.fish
fish: Expected a string, but found a redirection`

↪ > ls $HOMEBREW_PREFIX/bin/git-forgit
fish: Expected a string, but found a redirection

**Comment by cjappl** [comment]
Hmm, how about

'''
echo $HOMEBREW_PREFIX
'''

Not really sure what your output means. Can you tell via some other means (opening finder and going to the location) that those two files exist?

**Comment by cjappl** [comment]
Will be fixed once #379 is merged and we do a release to homebrew.

In the meantime I recommend just using the github repo directly. Thanks for reporting!!

**Comment by cjappl** [comment]
@Trid-collab please update forgit with brew and this should be fixed (I just checked it).

Please let me know if you still see the issue.

**Comment by Trid-collab** [comment]
Hi Chris,

Thank you. It works perfectly now. This was one tool which was hindering my
migration from zsh to fish.

I also checked it with fish and zsh in WSL in windows as well -where it
also works fine.

Regards
Tridib

**Comment by cjappl** [comment]
Enjoy fish!! I've been a convert for years and I love it.

Cheers
