### ISSUE TITLE
Forgit no longer allowing variables inside gitconfig for pager

### ISSUE THREAD

**Issue by blaineventurine** [wfxr/forgit#380]
## Check list

- [X] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [X] I have the latest version of forgit
- [X] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [X] zsh
    - [x] fish

## Problem / Steps to reproduce

I have my Git pager set to `pager = delta --side-by-side --width $(expr ${COLUMNS} - 10) --wrap-max-lines unlimited`. 

The newest version of Forgit no longer allows variables to be used - it will just display `error: unexpected argument '10)' found`.
If I set it to `--width ${COLUMNS}`, it tells me `Invalid value for width: "${COLUMNS}" is not an integer`

Bpyassing Forgit and just calling `git diff` shows everything as I would expect.

**Comment by cjappl** [comment]
Thanks for reporting! We had a big refactor recently and expected a little churn. 


@sandr01d I didn't have time to fully get into this tonight, but I can repro on mac/fish. I bisected and found this was the commit that introduced it:

https://github.com/wfxr/forgit/commit/bfffda68d80aae31f51f683371f2c642ba33b0e8

**Comment by sandr01d** [comment]
Can reproduce and found the issue. I've created #381 to start a discussion on how to solve this with more details. This does not work for the the enter commands though (e.g. pressing enter in `gd` or `gss` to view a single file/stash) with the pager configuration provided, but this wasn't working before the last release, so I would argue this to be out of scope - at least for now.

**Comment by blaineventurine** [comment]
Thanks a ton for the quick reply! I'm glad it's reproducible and not just a problem with me.
