### ISSUE TITLE
xargs: realpath: No such file or directory

### ISSUE THREAD

**Issue by skylarmb** [wfxr/forgit#39]
Just installed forgit using zplug. When running `gd` i get the following error. How can I debug this? other forgit commands seem to work fine

```
xargs: realpath: No such file or directory
```

**Comment by wfxr** [comment]
It seems the `realpath` command does not exist in your system. What's your OS ?

**Comment by wfxr** [comment]
@skylarmb `gd` use `realpath` to convert absolute path to relative path which is shorter and easier to browse. `realpath` is a gnu standard command but some os like mac does not install it by default.
I will add some code to avoid this convert when `realpath` was not installed. But if you want the relative paths you can install the `realpath` command. (most gnu commands include `realpath` exists in homebrew package named `coreutils`)

**Comment by skylarmb** [comment]
👏 thanks!!
