### ISSUE TITLE
Add command for git clean

### ISSUE THREAD

**Issue by paranoidi** [wfxr/forgit#40]
Hi,

Since git clean does not currently have inclusion filter, is there any chance you might add some convenient helpers for git clean? :)

**Comment by cjappl** [comment]
Is there some functionality you want besides the "gclean" command? Please describe what kind of feature you're looking for

**Comment by cjappl** [comment]
Closing if we don't hear from you in the next few days @paranoidi

**Comment by cjappl** [comment]
Closing, no response from requester. If you have a suggestion, please re-file it using the new template and provide more information!

**Comment by paranoidi** [comment]
@cjappl apologies for the ticket noise, I was sure that this did not exists. Now I feel just stupid. Keep up the good work!

**Comment by cjappl** [comment]
all good man, always happy to hear feedback!
