### ISSUE TITLE
Add an .editorconfig file

### ISSUE THREAD

**Issue by suft** [wfxr/forgit#403]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
Add an `.editorconfig` to help maintain consistent coding styles and conventions in the codebase.

**Comment by carlfriedrich** [comment]
@suft Thanks for your suggestion. Do you already have an editorconfig file you could provide? 

I actually don't have one. What about @cjappl @wfxr @sandr01d ?

**Comment by suft** [comment]
@carlfriedrich I can write one
