### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by carlfriedrich** [wfxr/forgit#410]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce

The default branch name on GitHub has been changed to `main` a few years ago [due to cultural sensitivity](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main). I am voting for changing it in forgit as well. Any opinions?

**Comment by sandr01d** [comment]
I don't have a strong opinion on this in either direction. In case we go with this, we'll have to make sure to also update a few instructions in the README.md and a few links, such as in our PR template.

**Comment by cjappl** [comment]
no objections from me, this is one of the last repos i interact with on a regular basis that is still `master`

**Comment by wfxr** [comment]
It seems that we have no objection to this. I will make this change shortly.

**Comment by carlfriedrich** [comment]
@wfxr Great, thanks a lot!
