### ISSUE TITLE
gd does not use the screen space properly

### ISSUE THREAD

**Issue by dtinhvo** [wfxr/forgit#411]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

## Problem / Steps to reproduce
- Install forgit 
- use `delta` for pager
- Use `gd`
Issues:
- fzf diffed file results does not start from the current command line location, but from the bottom
![image](https://github.com/user-attachments/assets/e1ebecb1-456b-493e-893c-943c9642ad12)
- In the above example, gd with a commit selected (`HEAD^`) disables preview keybinding (`?`)
- Hitting `enter` does not use the whole screen for the pager, cropped horizontally
![image](https://github.com/user-attachments/assets/10c7f699-3c42-41f6-867c-140b8571848b)

Further information:
I am using wezterm over ssh domain. Without ssh, the disabled preview keybinding. I also suspect this can be a less pager problem (that my delta pager uses)

**Comment by sandr01d** [comment]
> fzf diffed file results does not start from the current command line location, but from the bottom

This is just how fzf works. You can move this to the top of your terminal, e.g. by setting `FORGIT_FZF_DEFAULT_OPTS="--padding=0,0,49%"` but AFAIK there is no option in fzf to start from the current command line location.

> In the above example, gd with a commit selected (HEAD^) disables preview keybinding (?)

Could you please explain what exactly you mean with this? I can toggle the preview with `?`, which is the intended behavior, see

https://github.com/wfxr/forgit/blob/7a40a11e795f42c851eefbb2fd39419383c66ccd/bin/git-forgit#L34C1-L34C26

> Hitting enter does not use the whole screen for the pager, cropped horizontally

This is an issue with how the side-by-side diff is implemented in delta. This has already been raised in #121 and you should be able to work around it with https://github.com/wfxr/forgit/issues/121#issuecomment-968118124.

**Comment by dtinhvo** [comment]
> This is just how fzf works. You can move this to the top of your terminal, e.g. by setting FORGIT_FZF_DEFAULT_OPTS="--padding=0,0,49%" but AFAIK there is no option in fzf to start from the current command line location.

That is unfortunate, I hoped that this could be an option since fzf's usual cd-widget and file-widget starts from the command line location

> Could you please explain what exactly you mean with this? I can toggle the preview with ?, which is the intended behavior, see

I would like to close this complaint at the moment. I know that `?` is default behaviour, and it does work locally (my terminal emulator on local environment), but does not work when I ssh into a remote machine (my terminal emulator on remote). However, I found out recently that my WezTerm is hanging from the particular ssh session I am attaching to, so this may be a WezTerm problem first. 

> This is an issue with how the side-by-side diff is implemented in delta. This has already been raised in https://github.com/wfxr/forgit/issues/121 and you should be able to work around it with https://github.com/wfxr/forgit/issues/121#issuecomment-968118124.

Thank you! This is the solution of my main complaint. Using enter to view single file is much easier now, since I always split my screen horizontally and have limited screen space as a result.

**Comment by sandr01d** [comment]
> That is unfortunate, I hoped that this could be an option since fzf's usual cd-widget and file-widget starts from the command line location

I just did a bit of digging and it seems the cd-widget is simply using `--height 40%`. Maybe that is what you are looking for?
