### ISSUE TITLE
Support for fish?

### ISSUE THREAD

**Issue by cjappl** [wfxr/forgit#42]
Just getting in to FZF and found this! It looks killer.

Any chance of supporting fish in the future? I'm sure it'd unlock even more users!

**Comment by cjappl** [comment]
Merged and closed!

**Comment by rapha8l** [comment]
Hi
hash does not exist in fish

**Comment by cjappl** [comment]
Please file a new ticket including OS and fish version so I can address
this!

It works perfectly on my system, so I will need more details to fix it.

**Comment by rapha8l** [comment]
thanks
