### ISSUE TITLE
command format

### ISSUE THREAD

**Issue by adberard** [wfxr/forgit#44]
The current command format `forgit::command arg` is pretty odd, and doesnt accept options such as --help

Using an universal format like `forgit [--option] <command> [<args>]` and a standard gnu help could be a great addition for completion systems (so `compdef _gnu_generic forgit` could work, also we could use git completion to select branch and files)

https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html

**Comment by wfxr** [comment]
@adberard If you are talking about an independent program like [grv](https://github.com/rgburke/grv), I  think your suggestion makes sense.

But `forgit` is just a **small plugin** for the shell as you see. Essentially it's a set of aliases which are frequently used, but not a standalone program. And there is no complicated features need to be explained in detail. `README` and the source code is already enough.
