### ISSUE TITLE
Change default mapping of select all to ctrl+a?

### ISSUE THREAD

**Issue by cjappl** [wfxr/forgit#50]
Just wondering if there is a reason it's ctrl+r, I think ctrl+a is a little more common, and may be more intuitive

```
set FORGIT_FZF_DEFAULT_OPTS "
$FZF_DEFAULT_OPTS
--ansi
...
--bind='ctrl-r:toggle-all'    <------
...
$FORGIT_FZF_DEFAULT_OPTS
"
```

**Comment by wfxr** [comment]
@cjappl 
ctrl - a is a common shortcut for Linux, for moving the cursor to the beginning of the line. This is also the reason why `fzf` does not use `ctrl - a` as the default shortcut for `toggle all` action.

In my opinion `r` means reverse. Binding it to the toggle action is appropriate. I have found other projects to do the same, but I can’t recall which one.

however, you can add the binding in the `$FORGIT_FZF_DEFAULT_OPTS` if you prefer `ctrl - a`

**Comment by cjappl** [comment]
Cool, makes sense to me! Thanks for the explanation
