### ISSUE TITLE
Support pager program specified in global git config

### ISSUE THREAD

**Issue by Seirdy** [wfxr/forgit#51]
forgit should be able to use whatever program is specified by the git config `core.pager`.

I use [`delta`](https://github.com/dandavison/delta) as my git pager, and I work around the lack of support in forgit quite well by adding a faux `diff-so-fancy` shell script to my path that calls `delta`.

**Comment by wfxr** [comment]
@Seirdy Thank you.
It's a good suggestion. I will consider implementing it.

**Comment by wfxr** [comment]
Implemented. 

@Seirdy  You can update and try it.

**Comment by cjappl** [comment]
Committed and merged. Assigning back to you @wfxr, What I did was slightly different, you can see in the fish config.

Basically, I checked for a pager, if there was a pager I went with that

If not, fell back to diff-so-fancy

if not, fell back to cat

Not sure if you want to replicate on your side, or just remove diff-so-fancy! Let me know if you want it removed and I can take it out of the fish, I want to make sure we match as much as possible

**Comment by wfxr** [comment]
Hi @cjappl Thank you.

You can take a look at the [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy)'s README. If one uses diff-so-fancy they must set it as the git pager already. `delta` is the same. We can safely read the pager config from git and use it as `forgit`'s pager. If the pager is not set, the `diff-so-fancy` is not installed. So I made the simplifications on fallback judgements.

**Comment by cjappl** [comment]
Cool sounds good. We can probably close this then!

**Comment by Seirdy** [comment]
Thanks; I removed the faux `diff-so-fancy` script and forgit correctly uses `delta`!
