### ISSUE TITLE
[BUG] - fish throw an "hash" error

### ISSUE THREAD

**Issue by rapha8l** [wfxr/forgit#54]
Hi, on an up to date Void Linux system, fish, version 3.0.2
using "source ~/.config/forgit/forgit.plugin.fish" in ~/.config/fish/config.fish

I get

> ~/.config/forgit/forgit.plugin.fish (ligne 16) : 
> if not hash fzf > /dev/null 2>&1
>        ^
> du fichier source ~/.config/forgit/forgit.plugin.fish
> 	appelé à la ligne 331 du fichier '~/.config/fish/config.fish'
> 
> du fichier source ~/.config/fish/config.fish
> 	appelé pendant le démarrage
> 
> ~/.config/forgit/forgit.plugin.fish (ligne 32) : 
> hash emojify >/dev/null 2>&1 && set forgit_emojify '|emojify'
> ^
> du fichier source ~/.config/forgit/forgit.plugin.fish
> 	appelé à la ligne 331 du fichier '~/.config/fish/config.fish'
> 
> du fichier source ~/.config/fish/config.fish
> 	appelé pendant le démarrage
> 

Indeed hash is not a builtin command and does not exist otherwise in my system

Thanks

**Comment by cjappl** [comment]
@rapha8l please pull the latest from master and see if that works for you! Using something that should be built-in to fish now.

Please keep filing bugs as you find them, I'm pretty new to scripting fish so I'm sure you will run into issues! Your testing and bug reports are appreciated :)

**Comment by puddyput** [comment]
Works for me now, thanks a bunch!

**Comment by cjappl** [comment]
awesome!! That goes for you as well @puddyput, very happy to have more fish testers on this thing. Don't hesitate to file any issues, or if you feel bold make a PR yourself.

**Comment by rapha8l** [comment]
hello

Thanks a lot for your quick fix !
Indeed it works great
Have a nice day
