### ISSUE TITLE
[BUG] - FZF not found

### ISSUE THREAD

**Issue by benavern** [wfxr/forgit#57]
**Describe the bug**
I have this in my ~/.zshrc
```
# fzf & forgit
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
which fzf
hash fzf &>/dev/null || echo "hey I am working!"
[ -f ~/.forgit/forgit.plugin.zsh ] && source ~/.forgit/forgit.plugin.zsh
```
but when I restart my terminal here is the outpout:

```
/home/zezen/.fzf/bin/fzf
hey I am working!
[Warn] FZF not found and is requried for forgit
```

**To Reproduce**
I don't see anything I could have done wrong ...

**Expected behavior**
That it works (as they say)

**Screenshots**
![](http://i.imgur.com/YYEnzpz.png)

**Desktop (please complete the following information):**
 - OS: 
```
Operating System: elementary OS 5.0 Juno
          Kernel: Linux 4.15.0-70-generic
    Architecture: x86-64
```
 - Shell: zsh
 - Shell Version: zsh 5.4.2 (x86_64-ubuntu-linux-gnu)
 - Any other terminal config? antigen in zsh but not using it for fzf or forgit

**Comment by wfxr** [comment]
Hi @benavern  Your problem seems to be that fzf is not being installed correctly. This is not a bug about forgit.

You have this line in `zshrc`:
```
hash fzf &>/dev/null || echo "hey I am working!"
```
It means if the `fzf` can be found in PATH `hash fzf &>/dev/null` will return true and you shouldn't see the message "hey I am working!". But it actually appears, as you can see.

 You need check the [installation instructions for fzf](https://github.com/junegunn/fzf#using-git) carefully. From the description you given I guess may be you manually downloaded fzf, but did not run its install command:
```
~/.fzf/install
```

**Comment by benavern** [comment]
Hi, thanks for your answer.
fzf is installed, I ran it multiple times, and when I copy-paste the forgit line in my terminal once it is ready, forgit starts working. seems that something is maybe asynchronous in fzf initialization...

I tried to delete everything and install it differently, here are my steps:
- clone fzf in `~/.fzf`
- run `~/.fzf/install` (answered y to all the questions)
- add `antigen bundle 'wfxr/forgin'` in my antigen conf file (`~/.antigenrc`)
- source my antigen conf file so that the antigen plugin is installed
- start a fresh terminal window

It still doesn't work, but no warning message is displayed.
here are the full conf files: 
![](http://i.imgur.com/3UNksXW.png)

Do I have to source the forgin antigen plugin somewhere ?

**Comment by wfxr** [comment]
Weird... I don't know why antigen doesn't load `forgit`.

Can you run the following commands one by one and list the outputs here?

- `which fzf`
- `forgit::log`
- `glo`

**Comment by benavern** [comment]
```
 ~  ⬡ v10.16.3 
>_ cd Workspace/Open-Source/forgit

 ...Workspace/Open-Source/forgit   master ✔  ⬡ v10.16.3 
>_ which fzf
/home/zezen/.fzf/bin/fzf

 ...Workspace/Open-Source/forgit   master ✔  ⬡ v10.16.3 
>_ forgit::log

 ✘  ...Workspace/Open-Source/forgit   master ✔  ⬡ v10.16.3 
>_ glo

```
-  `forgit::log` gives an error
- the `glo` output is the git log alias from the git zsh plugin, not the one from forgit
![](http://i.imgur.com/UoHyQ8G.png)

**Comment by wfxr** [comment]
At least one problem has been identified that forgit's default alias `glo` was overwriten by `git` plugin. You should specified another alias or disable the alias from git zsh plugin or make sure `forgit` was loaded after zsh `git` plugin.

And what the error `forgit::log` shows?

**Comment by benavern** [comment]
once I source forgit manualy, the aliases for forgit are working well so I think nothing to do by me here, just sourcing forgit after the zsh git plugin.

`forgit::log` is not displaying any info, it just returns a non 0 exit code

**Comment by wfxr** [comment]
Sorry but I can't reproduce what you described. I can hardly understand since `glo` is only an alias for `forgit::log`. It cann't work if `forgit::log don't work`.

**Comment by wfxr** [comment]
@benavern 
I will close this issue because this is unlikely to be a bug for forgit. But if you find more clues, feel free to open it again.

**Comment by horseinthesky** [comment]
I've just installed `forgit` and have the same issue:
```
[Warn] FZF not found and is required for forgit
```

`fzf` is installed via `vim-plug` and I've tried to reinstall it several times.

**Comment by cjappl** [comment]
Can you install it with your normal package manager, not vim-plug? 

I would guess you just installed the fzf vim plugin, not fzf itself

**Comment by horseinthesky** [comment]
> Can you install it with your normal package manager, not vim-plug?
> 
> I would guess you just installed the fzf vim plugin, not fzf itself

No, it is installed and working
![image](https://user-images.githubusercontent.com/19948672/69409053-4b7c4400-0d19-11ea-9135-9da2e69d1406.png)

**Comment by wfxr** [comment]
@horseinthesky Did you load `forgit` before adding `fzf` to `$PATH` ?

**Comment by horseinthesky** [comment]
> @horseinthesky Did you load `forgit` before adding `fzf` to `$PATH` ?

Yes. Thas was the case. `oh-my-zsh` was loading plugin first and then `fzf` was added to the `$PATH`.
Fixed it and it works perfectly fine now.
Thank you!

**Comment by benavern** [comment]
How did you fix it ? could you share your configuration files ? I didn't manage to make it work yet ...

**Comment by horseinthesky** [comment]
> How did you fix it ? could you share your configuration files ? I didn't manage to make it work yet ...

The thing is `forgit.plugin.zsh` executes `hash fzf &>/dev/null` and before it does it you need to have `fzf` in your `$PATH`.

I am using `oh-my-zsh` to load plugins and this is my `.zshrc`:
https://github.com/horseinthesky/dotfiles/blob/master/files/.zshrc

You can see I firstly do:
https://github.com/horseinthesky/dotfiles/blob/7b098009bc5e1ae7b675ddd2443c105d55de60fe/files/.zshrc#L54

And then I load the plugins:
https://github.com/horseinthesky/dotfiles/blob/7b098009bc5e1ae7b675ddd2443c105d55de60fe/files/.zshrc#L116

**Comment by wfxr** [comment]
@horseinthesky You are welcome.

And for two reasons, I think it is not necessary to check if `fzf` exists during loading. I will remove this check after a while. You can keep your configuration unchanged.

1. We have no way(and there is no need) to make `fzf` exist in $PATH before `forgit` is being loading.
2. If we do not check and user does not actually install fzf, the shell will still give a warning that `fzf` does not exist.

@cjappl

**Comment by benavern** [comment]
Wow, thanks! 
just went from this: 
![](http://i.imgur.com/4TphBvE.png)

to this:
![](http://i.imgur.com/BhUtKBp.png)

and it is now working well!

so maybe the readme has to be clearer about this: 
load fzf before zsh, but load forgit after it

I'll close the issue since that fixed mine :)

**Comment by horseinthesky** [comment]
@wfxr Could you help me with one small thing?

I want to keep `forgit` working when switching to `root` with `sudo -E -s` but it keeps saying me:
```
[Warn] FZF not found and is required for forgit
```

It is not a big deal but I just want to know what I am doing wrong.

**Comment by wfxr** [comment]
Have you updated to the latest version? If so, what is the output of `echo $PATH`?
Does it contain `fzf`'s location? @horseinthesky

**Comment by horseinthesky** [comment]
> Have you updated to the latest version? If so, what is the output of `echo $PATH`?
> Does it contains `fzf`'s location? @horseinthesky

I have just noticed you updated an hour ago. With the latest version it is working after `sudo -E -s` too. Thanks.

**Comment by wfxr** [comment]
That's OK. @horseinthesky
