### ISSUE TITLE
Can we simplify the issue template? 

### ISSUE THREAD

**Issue by wfxr** [wfxr/forgit#59]
@cjappl  Thank you for your excellent work to add issue templates for the project. I like it very much.

Now I have a suggestion that can we do some simplification on it considering the size and type of this project?

Maybe we can take [`fzf`'s template](https://github.com/junegunn/fzf/blob/master/.github/ISSUE_TEMPLATE.md) as the template of our issue template. It's simpler and more suitable for this project. What do you think?

**Comment by cjappl** [comment]
Yes sounds great! I will do that right now

**Comment by cjappl** [comment]
@wfxr do you mean our PR template (https://github.com/wfxr/forgit/blob/master/.github/pull_request_template.md) or the bug/feature request template (https://github.com/wfxr/forgit/tree/master/.github/ISSUE_TEMPLATE)

I think the bug and feature request ones are relatively simple, but the PR one could definitely be brought down in size!

**Comment by wfxr** [comment]
@cjappl

In fact I think the Issue template should be simplified(and it should be up to the maintainer, not the user to determine whether a issue is a question, a bug, a feature request, or just a simple discussion.). 

This will lower the threshold for people to ask questions or submit bugs.

Just have a simple issue template like `fzf`'s is enough I think.

PR involves the merging and updating of code, so it's proper to be some rigorous.

**Comment by cjappl** [comment]
Sounds good! I will address this in a few days, or feel free to do it yourself! Those ones both live in the .github folder, and you can easily edit on the web.

If you end up doing it, feel free to tag me for review, otherwise I'll do it when I'm free from vacation

**Comment by wfxr** [comment]
@cjappl Ok, thank you. Have a good vacation!

**Comment by cjappl** [comment]
LGTM closing
