### ISSUE TITLE
Fish use of unsupported command chaining like "&&" and "||"

### ISSUE THREAD

**Issue by mwelsch-tgm** [wfxr/forgit#61]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Steps to reproduce
- Copy & Paste `forgit.plugin.fisher` to `~/.config/fish/forgit.plugin.fish`
- add `source ~/.config/fish/forgit.plugin.fish` to the fisher config
- reload terminal
- also happens when using the "online" version `source (curl -Ss https://raw.githubusercontent.com/wfxr/forgit/master/forgit.plugin.fish | psub)`
## Problem
Use of unsupported command chaining. When reloading the terminal I get the following errors:
```
~/.config/fish/forgit.plugin.fish (line 27): Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
type -q emojify >/dev/null 2>&1 && set forgit_emojify '|emojify'
                                 ^
from sourcing file ~/.config/fish/forgit.plugin.fish
	called on line 35 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called on line 1 of file -

in function “reload”
	called on standard input

source: Error while reading file “/home/fullname/.config/fish/forgit.plugin.fish”
```
I decided to do a quick&dirty fix by replacing all `&&` with a `;` with vim. I wanted to see if this was the only problem, even though it would probably break the functionality of the script. Then I got the following error:
```
~/.config/fish/forgit.plugin.fish (line 31): Unsupported use of '||'. In fish, please use 'COMMAND; or COMMAND'.
    forgit::inside_work_tree || return 1
                              ^
from sourcing file ~/.config/fish/forgit.plugin.fish
	called on line 35 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called on line 1 of file -

in function “reload”
	called on standard input

source: Error while reading file “/home/fullname/.config/fish/forgit.plugin.fish”
```
Applying another dirty fix by replacing `||` with `;` I got the follwing message:
```
~/.config/fish/forgit.plugin.fish (line 47): Expected a command, but instead found end of the statement
    eval "git log --graph --color=always --format='%C(auto)%h%d %s %C(black)%C(bold)%cr' $argv $forgit_emojify" |
        env FZF_DEFAULT_OPTS="$opts" fzf
                                                                                                                 ^
from sourcing file ~/.config/fish/forgit.plugin.fish
	called on line 35 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

source: Error while reading file “/home/fullname/.config/fish/forgit.plugin.fish”
.v: No such file or directory
```
You can fix those by 
- removing the new line character after the pipe
- add a `\` to the end of line

Errors occourd on line
- 47
- 71
- 87 and following
- 193

As expected I removed all interpretation errors, but broke the program. `ga` simply exits with the return code 1

**Comment by cjappl** [comment]
Can you please post your OS and fish version? This is working for others,
as well as myself so I'd like to understand how your configuration is
different!

Thank you

**Comment by mwelsch-tgm** [comment]
Hello,
I had fish version 2.7.1 installed, works perfectly fine on version 3.0.2. I fucking hate fedora for providing apps in outdated version rather then removing them completly
cheers

**Comment by cjappl** [comment]
Awesome! That's kind of what I was suspecting. I'll research into if we
should move to "and" and "or" instead of "&&" and "||"

I remember there being some subtle differences, may be worth doing even
though this is fixed by an upgrade.

Thanks for reporting back
