### ISSUE TITLE
Failed to read /dev/tty when trying to execute "glo"

### ISSUE THREAD

**Issue by dawidd6** [wfxr/forgit#64]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

This is what happens when I try to execute `glo` alias.

```
➜  dawidd6/homebrew-tap master ✗  glo
echo {} |grep -Eo '[a-f0-9]+' |head -1 |xargs -I% git show --color=always %  | diff-so-fancy | less --tabs=4 -RFX
Failed to read /dev/tty
➜  dawidd6/homebrew-tap master ✗  [3;1R
```

Does not happen with `gd` and `ga` for example.

**Comment by cjappl** [comment]
Thanks for reporting! I will look at this as soon as I can :)

**Comment by dawidd6** [comment]
Related issue: https://github.com/junegunn/fzf/issues/1486

**Comment by cjappl** [comment]
@dawidd6 would you please check if this shows the error?

git log --graph --color=always --format='%C(auto)%h%d %s %C(black)%C(bold)%cr' | fzf

**Comment by dawidd6** [comment]
No error, but shell color codes are showing. Better use `--color=never`.

**Comment by cjappl** [comment]
Alright I'm having a very hard time reproing (albeit on another OS and setup). I would suspect that this isn't a bug with us, however, as we just basically harness the other tools to use.

We don't explicitly use /dev/tty anywhere, so it must be happening in one of the other commands we call.

@wfxr do you have any thoughts on this?

**Comment by wfxr** [comment]
@cjappl Agree with you.

@dawidd6 Can you run the following commands and show us the outputs?

1. 
```bash
fzf --version
echo $FORGIT_FZF_DEFAULT_OPTS
echo $FZF_DEFAULT_OPTS
```

2. (Preferably screenshot)
```bash
echo -e "Default \e[33mYellow" |FZF_DEFAULT_OPTS='' fzf
```

3. (Preferably screenshot)
```bash
echo -e "Default \e[33mYellow" | fzf --ansi
```

**Comment by cjappl** [comment]
@dawidd6 going to close this if we don't hear from you soon!

**Comment by dawidd6** [comment]
@wfxr 

1.
```
➜  ~/ansible master ✓  glo
Failed to read /dev/tty
➜  ~/ansible master ✓  fzf --version
0.20.0 (brew)
➜  ~/ansible master ✓  echo $FORGIT_FZF_DEFAULT_OPTS


--ansi
--height='80%'
--bind='alt-k:preview-up,alt-p:preview-up'
--bind='alt-j:preview-down,alt-n:preview-down'
--bind='ctrl-r:toggle-all'
--bind='ctrl-s:toggle-sort'
--bind='?:toggle-preview'
--bind='alt-w:toggle-preview-wrap'
--preview-window='right:60%'


➜  ~/ansible master ✓  echo $FZF_DEFAULT_OPTS

➜  ~/ansible master ✓ 
```

2.
![image](https://user-images.githubusercontent.com/9713907/71577725-926a1000-2af5-11ea-86de-db2c564954c5.png)

3.
![image](https://user-images.githubusercontent.com/9713907/71577750-a44bb300-2af5-11ea-9d55-b3dc577a27a2.png)

**Comment by wfxr** [comment]
@dawidd6 I originally suspected that the environment variables might be overwritten incorrectly which causing the colors to wrongly displayed. But that doesn't seem to be the case now. I think @cjappl 's conclusion is right. This is unlikely to be a bug introduced by `forgit`. Sorry for not helping you. I will close this issue. But if you have any new findings please feel free to reopen this issue.

**Comment by cjappl** [comment]
Hey @dawidd6 This has been tracked now in #87 There does seem to be a significant issue in Fish using fzf, that is breaking our stuff. If you want, you can roll back to fish 3.0 until they get that fixed
