### ISSUE TITLE
Preview not working in sub-directories

### ISSUE THREAD

**Issue by ea2809** [wfxr/forgit#65]
## Check list

- [X] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [X] I have the latest version of forgit
- [X] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [X] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [X] zsh
    - [ ] fish

## Problem / Steps to reproduce

Related with issue #29 and #39
There is now preview when you are in a subdirectory.
After searching where the solution for #29 changed, I found it was removed in PR #58.

It this the expected behavior? Am I missing something?

**Comment by wfxr** [comment]
I guess it may be caused by the incompatibility of `sed` between linux and mac.

I don't have a mac computer at hand now. Can you run the following command in your shell and show me the output here? @ea2809 

```bash
echo 'M  a/b/c/d' | sed 's/^\(.\)[[:space:]]\+\(.*\)$/[\1]  \2/'
```

**Comment by wfxr** [comment]
@ea2809 I submitted a patch. It should fix the problem.

**Comment by ea2809** [comment]
@wfxr you are a genius. Thank for your time !! And for the fix 😃

The output of the command is:
```
M  a/b/c/d
```
