### ISSUE TITLE
Show content of untracked files when previewing with `ga`

### ISSUE THREAD

**Issue by amitlevy21** [wfxr/forgit#66]
Hi,

Thank you for making this tool!

## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

1. Create a new file named `foo` that contains `hello`
2. Type `ga`
3. The file foo appears in the list but the preview for it is empty, it does not show `hello`

It would be nice to have this because once I type `ga` and see a new untracked file I can decide whether I need to add it or ignore it in .gitignore.

I can see why this can be an issue: What would be the expected behaviour when adding a new untracked folder? Maybe `ga` should list all the untracked files and not just their parent directory?

![image](https://user-images.githubusercontent.com/28672915/71309729-26f8b200-2414-11ea-9aaf-68e0b0b65cf9.png)

**Comment by wfxr** [comment]
Sounds good to me. Thanks for your suggestion @amitlevy21 !

**Comment by wfxr** [comment]
@amitlevy21 Implemented by pr #67. You can now update and try if it works as expected.

**Comment by amitlevy21** [comment]
@wfxr Perfect! Thanks for responding so fast!

**Comment by cjappl** [comment]
I'm going to reopen this to implement in fish :)

**Comment by cjappl** [comment]
Done :)
