### ISSUE TITLE
Remove explicitly untracked files from ga

### ISSUE THREAD

**Issue by antoniy** [wfxr/forgit#68]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

With the recent introduction of untracked files preview in PR #67 there is a problem concerning showing untracked files even if the user explicitly disabled that functionality in `.git/config` with this configuration:

```cfg
[status]
  showUntrackedFiles = no
```

My use-case - I have a repo for my home directory that I use for my dotfiles. I've explicitly disabled untracked files in `status` as my entire home directory contents will be flagged as untracked. With that recent change `ga` will have to load 400k files before it present me with fzf picker which makes it unusable.

Solution - remove `--untracked-files` argument from both `git status` commands in `forgit::add()` function. It should work as before but it will allow people to disable them from git config.

**Comment by wfxr** [comment]
Hi @antoniy Sorry but for some reasons I will not accept your suggestion.

1. We can not preview and add the untracked files individually If we remove the `--untracked-files` option. see #66 

2. `ga` currently use `git status` to get the files which **can be added**. But it doesn't means `ga` must use `git status` and must respect every config of `git status`. In theory we can implement `ga`  without using `git status` at all. Files which can be added to git should be listed in `forgit::add`, just as `git add`'s behavior. Suppress untracked files for `git status`'s output do not affect `git add` as well as `ga`.

3. Actually I don't think use whole home directory as a git repo is a good way. Maybe what you need is a dotfiles repository to sync all your configurations. You'd better create a dedicated repo and move **only configuration files** to it then link them to their original position. If for some reason you have to stick to what you are doing please add an ignore file to describe which files should be added and/or which files should not be added.

**Comment by antoniy** [comment]
Hello @wfxr 
1. I'm sorry but I don't follow what the problem is. The ability to preview the untracked files is the change you've implemented in the `--preview` fzf argument and not the `git status` command. 

```diff
diff --git a/forgit.plugin.zsh b/forgit.plugin.zsh
index 15e7ec7..74f3d22 100755
--- a/forgit.plugin.zsh
+++ b/forgit.plugin.zsh
@@ -59,16 +59,20 @@ forgit::add() {
     opts="
         $FORGIT_FZF_DEFAULT_OPTS
         -0 -m --nth 2..,..
-        --preview=\"git diff --color=always -- {-1} | $forgit_pager\"
+        --preview=\"if (git status --porcelain -- {-1} | grep '^??') &>/dev/null; then  # diff with /dev/null for untracked files
+                        git diff --color=always --no-index -- /dev/null {-1} | $forgit_pager | sed '2 s/added: /untracked: /'
+                    else
+                        git diff --color=always -- {-1} | $forgit_pager;
+                    fi\"
         $FORGIT_ADD_FZF_OPTS
```

Setting the option `--untracked-files` doesn't change anything for a normal user as it is the default - untracked files are shown by default in `git status`. 

From `git-status` man page:
```man
-u[<mode>], --untracked-files[=<mode>]
           Show untracked files.

           The mode parameter is used to specify the handling of untracked files. It is optional:
           it defaults to all, and if specified, it must be stuck to the option (e.g.  -uno, but
           not -u no).
```
But on the other hand, it doesn't honor the explicit configuration of some users to ignore the untracked files. My use-case is not the only one. In my practice, I needed that option multiple times in a development environment.

So locally I've removed the `--untracked-files` parameters and kept your `--preview` function changes and untracked files preview is working normally.

2. Sure you can implement it as you wish but the current implementation in my mind is saner as it integrates exactly with user's git preferences (don't know why you underestimate that value) and is way more useful. If not for that, people can just use fzf `Ctrl-T` with some nice defaults in `FZF_DEFAULT_COMMAND`/`FZF_DEFAULT_OPTS` and be done with it.

3. Managing dotfiles repo for years, I found for myself that the whole linking/installing/managing configuration files on 2 places at once is an overkill experience. When I switch to this method, which is a variation of what's described in this [article](https://www.atlassian.com/git/tutorials/dotfiles), I had nothing but a great experience with my dotfiles repo. And also I preserve the config files structure the way it is supposed to be without thinking about it.

**Comment by wfxr** [comment]
Hi @antoniy Thanks for your feedback.

> 1. I'm sorry but I don't follow what the problem is. The ability to preview the untracked files is the change you've implemented in the --preview fzf argument and not the git status command.

I think we look at this issue from different view. In my view not showing untracked files in some scenarios is a bug existed in the former implementation. `ga` is an interactive simulation of the` git add` command, not `git status`. So if one file can be added using `git add`, `ga` has no reason not accepting it. This also means if there is an option make `git add` not accept some untracked files, `ga` should support it too. In fact this mechanism is already exists. It's **.gitignore**.

> 2. Setting the option --untracked-files doesn't change anything for a normal user as it is the default - untracked files are shown by default in git status.

In fact it does. Just do a little test (with default config for status) what's the difference :
```bash
# go to a git repo
mkdir foo && touch foo/bar1 foo/bar2 foo/bar3
git status --short
git status --short --untracked-files
```

> 3. Managing dotfiles repo for years, I found for myself that the whole linking/installing/managing configuration files on 2 places...

Of course, each way has its own reason. My intention is not to convince you to use the dotfiles way. If the home as repo way is more suitable for you, just use it. You may think of adding an ignore file to tell git you don't want to add those tons of untracked files into repo.

@cjappl How do you think about this?

**Comment by antoniy** [comment]
> I think we look at this issue from different view...

Okay, I understand your perspective from an ideological point of view and I respect that. Maybe I'll just use a custom solution that's more aligned for my use-cases and workflow. 

> In fact it does. Just do a little test (with default config for status) what's the difference

I can see the technical problem you are pointing here. I was just too used to see that behavior for untracked directories in `git status` but you're right that generic `ga` should show those files.

**Comment by wfxr** [comment]
@antoniy 🤝 Glad we reached an agreement! 

> Okay, I understand your perspective from an ideological point of view and I respect that. Maybe I'll just use a custom solution that's more aligned for my use-cases and workflow.

Sure since the script is quiet simple you can paste and overwrite function `forgit::add` in your `zshrc` if you find other parts are ok to you.
