### ISSUE TITLE
git log --graph edges point the wrong way

### ISSUE THREAD

**Issue by jcassee** [wfxr/forgit#71]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

The git log viewer calls `git log --graph`. Because the commits are shown bottom-up, the graph edges point the wrong way. See for example the log of forgit itself:

![Schermafdruk van 2020-01-29 15-34-26](https://user-images.githubusercontent.com/20749/73365787-1fe38000-42ad-11ea-9a10-f4bdd12555e9.png)

I don't think it is possible to have git output a reverse graph (`--graph` and `--reverse` are mutually exclusive). Maybe `--graph` should be omitted from the `git log` command?

**Comment by wfxr** [comment]
Thanks for your feedback @jcassee . I will check this after the vacation.

**Comment by wfxr** [comment]
Hi @jcassee . You're right, git doesn't provide such an option. There is a work around to make the graph reasonable when the commits are shown bottom-up:
```bash
forgit::log() {
    forgit::inside_work_tree || return 1
    local cmd opts full_opts flip
    cmd="echo {} |grep -Eo '[a-f0-9]+' |head -1 |xargs -I% git show --color=always % $* | $forgit_pager"
    opts="
        $FORGIT_FZF_DEFAULT_OPTS
        +s +m --tiebreak=index --preview=\"$cmd\"
        --bind=\"enter:execute($cmd | LESS='-R' less)\"
        --bind=\"ctrl-y:execute-silent(echo {} |grep -Eo '[a-f0-9]+' | head -1 | tr -d '\n' |${FORGIT_COPY_CMD:-pbcopy})\"
        $FORGIT_LOG_FZF_OPTS
    "
    full_opts="$FZF_DEFAULT_OPTS $opts"
    # if `reverse` option is NOT enabled, flip the '\' and '/' to make the log graph reasonable
    [[ $full_opts != *"--reverse"* ]] && [[ $full_opts != *"=reverse"* ]] && flip=true
    eval "git log --graph --color=always --format='%C(auto)%h%d %s %C(black)%C(bold)%cr' $* $forgit_emojify" |
        if [[ $flip == "true" ]]; then sed -e 's#/#{slash}#' -e 's#\\#/#' -e 's#{slash}#\\#'; else cat; fi |
        FZF_DEFAULT_OPTS="$opts" fzf
}
```
But before we have a better implementation I do not want to merge it into the code base. The main reason is we don't find a not complicated way to check if reverse option is enabled for fzf. The above code does simple string pattern matching but we are not sure if `--reverse` is set for fzf itself or some commands inside fzf instead (eg. --preview='...--reverse...' ).

**Comment by jcassee** [comment]
@wfxr Yeah, determining how fzf is used exactly is difficult. (By the way, the `sed` command would also switch slashes in the commit message, but that can be corrected.)

I know you did not want to, but maybe this is a good reason to allow customization of the `git log` command...?

**Comment by wfxr** [comment]
@jcassee `sed` replace only once per line unless `g` was specified at the end of replace pattern. So the above code will not switch slashes in the commit messages.

I understand your suggestion. Someone also mentioned this before. Because the extraction of the commit hash relies heavily on the output format of the git log I haven't adopted the suggestion before. But I will reconsider it.

I will keep this issue open and try to find a relatively reasonable solution.

**Comment by jcassee** [comment]
> `sed` replace only once per line unless g was specified at the end of replace pattern. So the above code will not switch slashes in the commit messages.

Good point. But that means it will only replace the _first_ slash, while there may be multiple. :smile: 

Anyway, I understand you want to think it over some more. It's a subtle issue.

**Comment by omares** [comment]
Hey any progress on this issue? :) Is there maybe an option to turn off the graph output?

**Comment by wfxr** [comment]
@omares @jcassee Sorry for the late reply. Now you can disable the log graph by set `FORGIT_LOG_GRAPH_ENABLE` to `false`.

**Comment by cjappl** [comment]
I believe we can close this now @wfxr, fish has the appropriate behavior as well

**Comment by jcassee** [comment]
Thanks, @wfxr!

**Comment by akaralar** [comment]
just as a heads up, I faced the same thing and added this to my `.zshrc`:
```
export FORGIT_LOG_FZF_OPTS='--reverse'
```

Before `fzf` or `forgit` is initialized. It displays correctly, only the typing box of `fzf` is at the top instead of bottom, but otherwise it is good.
