### ISSUE TITLE
ga - patch mode

### ISSUE THREAD

**Issue by loonies** [wfxr/forgit#75]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

Irrelevant

## Feature

Add a new command, or extand `ga` for patch mode (`git add --patch`).

**Comment by wfxr** [comment]
I think to completely solve the similar problems we shoud support pasing arguments to the final `git add` command. But there are some troubble because `ga` already take it's arguments as filters to only list files start with those paths.
