### ISSUE TITLE
Problems on displaying items on tmux

### ISSUE THREAD

**Issue by dansdantas** [wfxr/forgit#78]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

On tmux when i call forgit::add i got some errors on displaying files and no preview window on fzf
![image](https://user-images.githubusercontent.com/3410485/76858212-b5bf7400-6835-11ea-93d5-10323aa769cd.png)

If i call outside tmux error does not happens
![image](https://user-images.githubusercontent.com/3410485/76858287-db4c7d80-6835-11ea-8aca-881dec55691f.png)

I already tried changing $TERM variable, using tmux without any config file but no success. I know it's probably related to my configs, just wanted to know if this happens to you and if you know how to solve it.

Thanks!

**Comment by wfxr** [comment]
@dansdantas I don't have this problem. As you said, this should be a matter of tmux color configuration. I put my related `.zshrc` and `.tmuxconf` config here. Hope it does some help to you.

```zsh
export COLORTERM=truecolor
export TERM="tmux-256color"
```

```tmux
set -g  default-terminal   "tmux-256color"
set -sa terminal-overrides ',tmux-256color:RGB'
```

BTW my terminal is `Alacritty`. But I'm sure most of the other terminals should work without problem.

**Comment by dansdantas** [comment]
Yeah, it was the `term` value for kitty. Nothing related to forgit. What a wild ride. But thanks again.
