### ISSUE TITLE
Add support for viewing stashes

### ISSUE THREAD

**Issue by snowe2010** [wfxr/forgit#8]
Any way support could be added for viewing stashes? Currently I hate viewing stashes in SourceTree, and git's cli is suboptimal for it.

**Comment by wfxr** [comment]
Done by [0f5eeb5](https://github.com/wfxr/forgit/commit/0f5eeb5e12ef96c3543f75a5888f39e31a390e00).
You can update and try it.

**Comment by snowe2010** [comment]
Awesome! It works perfectly! Thanks a ton!
