### ISSUE TITLE
glo: doesn't display proper diffs with commit history slice

### ISSUE THREAD

**Issue by NullSense** [wfxr/forgit#85]
## Environment info

- OS
    - [x] Linux
- Shell
    - [x] zsh

## Problem / Steps to reproduce
`glo first_ref..last_ref`

e.g.: `glo 188a849b..73e5ca0d`

## Expected behavior:
Shows the commits only including that slice, and each diff is separate.

## Actual behavior:
Shows the commits only including that slice, but if you hover over any of them, it shows the diff of the whole slice itself, not each separate commit.

**Comment by wfxr** [comment]
Hi @NullSense As `REDME.md` descripted, `glo` accept **path** arguments to restrain the items listed in fzf (eg, glo main.go test.go). It's just a coincidence that commit ref can be used either.

But commit ref as the parameter for `glo` should be a good improvement. I will consider implementing it.

**Comment by wfxr** [comment]
@NullSense Implemented. Now can filter both refs and files like this:
`glo 188a849b..73e5ca0d -- main.go`

**Comment by wfxr** [comment]
@cjappl Ping...
This feature can be ported to `fish` version.

**Comment by cjappl** [comment]
Yep! I’m on it, sorry for the delay I should have told you I saw it :)

I’ll be working on it tomorrow, just had a weekend off.

Cheers! Hope you are staying safe and healthy.

**Comment by wfxr** [comment]
@cjappl That's all right.
I'm fine. And hope you are safe and healthy too friend!

**Comment by cjappl** [comment]
Good to go on fish :) Thanks for reporting @NullSense
