### ISSUE TITLE
glo: looking at a specific commit renders mouse unusable

### ISSUE THREAD

**Issue by NullSense** [wfxr/forgit#86]
- OS
    - [x] Linux
- Shell
    - [x] zsh

## Problem / Steps to reproduce
1. `glo ref`
2. press enter to select a commit ref
3. try selecting text with mouse for copy
4. can't select the text

So if you actually use `git show ref`, you are able to select text in the less output, but not with glo...

**Comment by wfxr** [comment]
@NullSense You should go to `fzf`'s repo to file the issue. It's nothing about `forgit` if you did a simple comparative test:
```bash
echo 'foo bar' | fzf --bind="enter:execute(echo {} | LESS= less)"
```

BTW you can try keep `shift` key pressed when selecting something from terminal.
