### ISSUE TITLE
Adding multiple files without quitting?

### ISSUE THREAD

**Issue by bs** [wfxr/forgit#92]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [x] fish

## Problem / Steps to reproduce

Is there a way to ```ga``` multiple files without exiting back to the shell? I looked through the scripts and nothing jumped out, but maybe I'm missing something!

**Comment by wfxr** [comment]
Hi @bs The default keybind for `fzf` to mark the selection is `tab`. Use `tab` multiple times to select multiple files. Also you can toggle all selections using `ctrl - r` which is defined by `forgit`.

**Comment by bs** [comment]
Oh, dope! I hadn't needed to use FZF for anything with multiples before.

Thanks for your work! 🥇

**Comment by wfxr** [comment]
You're welcome :)
