### ISSUE TITLE
FISH: gcf doesn't respect tab to multi select, will only checkout first file

### ISSUE THREAD

**Issue by cjappl** [wfxr/forgit#94]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Mac OS X

- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

When using `gcf` on fish with tab to multi-select, it will only select the first file, not multiple.

Multi select is working in `ga`, so just need to investigate why it's not working with the other

@wfxr when you get a chance, would you double check zsh and make sure this problem isn't there too?

**Comment by cjappl** [comment]
assigning myself so I can look into a fix when I have time

**Comment by wfxr** [comment]
Hi @cjappl zsh and bash should not have this issue:

https://github.com/wfxr/forgit/blob/0a817455d95f30aead9f4bc330e158e7b3d840ad/forgit.plugin.zsh#L111-L115
