### ISSUE TITLE
Bash syntax error when executing `ga` 

### ISSUE THREAD

**Issue by shyamsundar** [wfxr/forgit#96]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [ ] Linux
    - [x] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [ ] zsh
    - [x] fish

## Problem / Steps to reproduce

I added `source (curl -sSL git.io/forgit.fish | psub)` to my fish config file and trying the commands to explore `forgit`. When I try command `ga`, I get the below error. 
![Screen Shot 2020-06-20 at 2 37 59 PM](https://user-images.githubusercontent.com/1807780/85214647-a3684100-b322-11ea-9c3b-2d1812897f17.png)

The other commands are working fine.

**Comment by cjappl** [comment]
Thanks for the report! I’ll look at this asap, sorry for the problem :)

**Comment by cjappl** [comment]
Are you sure you're running this in fish?

It's strange that there is bash error, that shouldn't happen, it should all be run in fish.

can you do the following commands:

```
fish
source (curl -sSL git.io/forgit.fish | psub)
echo $SHELL
ga
```
and see if it works and what $SHELL is?

**Comment by shyamsundar** [comment]
Hi Chris, 

Thank you for your quick response. I was running it in `fish` configured in `iTerm`. But when I executed the commands you gave,`echo $SHELL` returned `/bin/bash`. I have changed the shell to `fish` using `chsh` and it is working as expected.  The diff loading seems to be a bit slow, but I'll play around with it some more. Definitely more useful tool.  

Thank you.

**Comment by cjappl** [comment]
Great! Glad that worked for you. Don't hesitate to reach out if you have any other issues :)
