### ISSUE TITLE
Forgit should start from the "top down" to allow users to tab through their options

### ISSUE THREAD

**Issue by cjappl** [wfxr/forgit#97]
## Check list

- [ ] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [ ] I have the latest version of forgit
- [ ] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [ ] Others:
- Shell
    - [x] bash
    - [x] zsh
    - [ ] fish

## Feature Request

When adding many files with `ga`, for example, it is nice to tab and add many of them at once.

Unfortunately when forgit starts, it begins at the bottom of the list, so the user must go all the way to the top of the list to tab down through the options

![Screen Shot 2020-07-01 at 9 41 31 AM](https://user-images.githubusercontent.com/14171107/86269832-28532600-bb7f-11ea-9089-b9f08fa6e004.png)

It would be nice if the cursor started at the top of the list, so the user just pushes "tab" multiple times to get through the whole list.

One option is to add
--reverse

to the FORGIT_FZF_DEFAULT_OPTS, but that reverses the whole layout. I'm not sure if we can just either switch the order of how tab works, or start at the top of the list!

**Comment by cjappl** [comment]
@wfxr any thoughts on this one? Requested by a friend and I think it's a great idea

**Comment by wfxr** [comment]
Hi @cjappl Start cursor at the top of the list in default layout is not possible but switch tab's behavior is easy:

```
--bind='tab:toggle+up'
--bind='btab:toggle+down'
```
(`btab` means Shift - Tab)

Or you can add `--reverse` to `FORGIT_ADD_FZF_OPTS` which only affects `forgit::add`'s behavior.

**Comment by cjappl** [comment]
Awesome! That's super useful. Added something to the README for it so new users could know. Thanks for the tip

**Comment by wfxr** [comment]
@cjappl Now `fzf` has a new layout `reverse-list`:

> reverse-list  Display from the top of the screen, prompt at the bottom

I find it meets your needs better.

**Comment by cjappl** [comment]
Awesome! thanks for thinking of me, that is exactly right!!

For future reference, anyone reading this, the command in fish to make forgit behave like this is:

`set FORGIT_FZF_DEFAULT_OPTS "$FORGIT_FZF_DEFAULT_OPTS --layout=reverse-list"`

You can put this anywhere in your fish config file!

**Comment by cjappl** [comment]
@wfxr How would you feel adding --layout=reverse-list to the default FZF_FORGIT_OPTS?

I have found this to be a big upgrade, and would support adding it for both zsh and fish.

**Comment by wfxr** [comment]
@cjappl But not few people are used to the `reverse` layout. I think it's better to respect user's own `FZF_DEFAULT_OPTS`. If they want to choose a different layout for `forgit` they still can override it in `FORGIT_FZF_DEFAULT_OPTS`. What do you think of it?

A related issue:
https://github.com/wfxr/forgit/issues/4#issuecomment-394098310

**Comment by cjappl** [comment]
I will leave it to you as the owner, but I definitely think the top down is a lot better experience!

Specifically because when I'm doing an action like "ga", it's nice to just tab down through the list, as opposed to shift+tab. It just feels like a more natural UI to me!

Whatever you decide, I fully support :) I just always forget to add the option on a new install and I have to remember to re-add it!

**Comment by wfxr** [comment]
@cjappl The main reason I think `reverse-list` should not be set by default in forgit is that it is not the only reasonable layout for forgit and pre-set it will overwrite one's global layout option for fzf, i.e `FZF_DEFAULT_OPTS`. In fact `reverse` (not `reverse-list`) is also a widely used layout and it is suitable for forgit too. If we do this people who use another layout like `reverse`  as fzf's default layout will get confused why only `forgit` shows a different layout. Finally they have to manually overwrite the layout overwrited by fogit again in `FORGIT_FZF_DEFAULT_OPTS`. This is what I want to avoid.

Thanks for your understanding and cooperation :)
